
const TariffDisplayParser = require('../../../../../../../backend/Transpiled/Gds/Parsers/Apollo/TariffDisplay/TariffDisplayParser.js');
const php = require('../../../../php.js');

class TariffDisplayParserTest extends require('../../../../../../../backend/Transpiled/Lib/TestCase.js') {
	provideTreeTestCases() {
		let $list;
		$list = [];
		$list.push([
			php.implode(php.PHP_EOL, [
				'FARES LAST UPDATED 03JUN  8:09 AM                              ',
				'>$D15JUNSFOBOS:RT                                                        SFO-BOS DEPART 15JUN                                  ',
				'PUBLIC/PRIVATE FARES FOR 2CV4                                  ',
				'U.S. PASSENGER FACILITY CHARGES / SURCHARGES MAY APPLY         ',
				'TAXES AND FEES MAY VARY DEPENDING ON THE BOOKED ITINERARY      ',
				'        USD     FARE         MIN/   XL  TVL DATES    TKT DATES ',
				'    CX  FARE    BASIS    AP    MAX  FE  FIRST/LAST   FIRST/LAST',
				'  1 VX  338.00R N21NR    21| --/--  ||     -/15JUNC     -/-    ',
				'  2 B6  338.00R SH2QBEN  21| --/--  ||     -/15JUNC     -/-    ',
				'  3-B6  338.00R SH2QBEN5 21| --/--  ||     -/15JUNC     -/-    ',
				'  4 AA  340.00R OA21ZNI5 21| --/--  ||     -/-          -/-    ',
				'  5 AS  340.00R RA21ZNI5 21| --/--  ||     -/-          -/-    ',
				'  6 AS  340.00R TA21ZNI5 21| --/--  ||     -/-          -/-    ',
				'  7 DL  342.00R VAUQA0MD 14| --/--  ||     -/-          -/-    ',
				'  8 SY  358.00R ZT14     14| --/--  ||     -/-          -/-    ',
				'  9 SY  358.00R ZT7      07| --/--  ||     -/-          -/-    ',
				' 10-B6  368.00R SH2QBEN6 21| --/--  ||     -/15JUNC     -/-    ',
				' 11 B6  368.00R UH2ABEN  21| --/--  ||     -/15JUNC     -/-    ',
				' 12-B6  368.00R UH2ABEN5 21| --/--  ||     -/15JUNC     -/-    ',
				' 13 VX  370.00R S21X7SP  21| --/--  ||     -/15JUNC     -/-    ',
				' 14 B6  370.00R SH2AUEN  21| --/--  ||     -/15JUNC     -/-    ',
				' 15-B6  370.00R SH2AUEN5 21| --/--  ||     -/15JUNC     -/-    ',
				' 16 B6  370.00R UH2AUEN  21| --/--  ||     -/15JUNC     -/-    ',
				' 17-B6  370.00R UH2AUEN5 21| --/--  ||     -/15JUNC     -/-    ',
				' 18-WN  380.77R NLAVPNRO 21| --/--  NR 10MAR/-          -/-    ',
				' 19 DL  398.00R XA7QA0MD 07| --/--  ||     -/-          -/-    ',
				' 20-B6  398.00R UH2ABEN6 21| --/--  ||     -/15JUNC     -/-    ',
				' 21-WN  400.75R NLAVPNRO 21| --/--  NR     -/31DECC     -/-    ',
				' 22-B6  400.00R SH2AUEN6 21| --/--  ||     -/15JUNC     -/-    ',
				' 23-B6  400.00R UH2AUEN6 21| --/--  ||     -/15JUNC     -/-    ',
				' 24 VX  408.00R S21QNR   21| --/--  ||     -/15JUNC     -/-    ',
				' 25 B6  408.00R OH2ABEN  21| --/--  ||     -/15JUNC     -/-    ',
				' 26-B6  408.00R OH2ABEN5 21| --/--  ||     -/15JUNC     -/-    ',
				' 27 UA  410.00R TAA21AGN 21| --/--  ||     -/-          -/-    ',
				' 28 DL  410.00R TAVNA0MY 21| --/--  ||     -/-          -/-    ',
				' 29 VX  410.00R S21QNR   21| --/--  ||     -/-          -/-    ',
				' 30 B6  410.00R OH2AUEN  21| --/--  ||     -/-          -/-    ',
				' 31-B6  410.00R OH2AUEN5 21| --/--  ||     -/-          -/-    ',
				' 32 B6  410.00R UH2AUEN  21| --/--  ||     -/-          -/-    ',
				' 33-B6  410.00R UH2AUEN5 21| --/--  ||     -/-          -/-    ',
				' 34-DL  420.00R VAUQA0MD 14| --/--  || 16MAY/17AUGC     -/-    ',
				'    TD:WCOM                                                    ',
				' 35 AA  432.00R QA14ZNI5 14| --/--  ||     -/-          -/-    ',
				' 36-WN  432.75R SLAUPNRO 14| --/--  NR 10MAR/-          -/-    ',
				' 37 AS  432.00R GA14ZNI5 14| --/--  ||     -/-          -/-    ',
				' 38 AS  432.00R VA14ZNI5 14| --/--  ||     -/-          -/-    ',
				' 39-B6  438.00R OH2ABEN6 21| --/--  ||     -/15JUNC     -/-    ',
				' 40-B6  440.00R OH2AUEN6 21| --/--  ||     -/-          -/-    ',
				' 41-B6  440.00R UH2AUEN6 21| --/--  ||     -/-          -/-    ',
				' 42 DL  442.00R TAUUA0MD 14| --/--  ||     -/-          -/-    ',
				' 43-WN  452.77R SLAUPNRO 14| --/--  NR     -/31DECC     -/-    ',
				' 44 AS  458.00R G14VN5   14| --/--  ||     -/-          -/-    ',
				' 45 DL  470.00R VAUQA0C1 14| --/--  || 16MAY/-          -/-    ',
				' 46-WN  470.75R MLAUPNRO 14| --/--  NR 10MAR/-          -/-    ',
				' 47 UA  476.00R TFA14AGN 14|  V/--  ||     -/-          -/-    ',
				' 48 DL  476.00R UFUNA0MY 14|  V/--  ||     -/-          -/-    ',
				' 49-DL  476.00R XA7QA0MD 07| --/--  || 16MAY/17AUGC     -/-    ',
				'    TD:WCOM                                                    ',
				'OTHER FARES EXIST-DO MORE SPECIFIC $D                          '
			]),
			{
				'result': {
					'0': {
						'lineNumber': 1,
						'isRoundTrip': true,
						'airline': 'VX',
						'fare': '338.00',
						'fareBasis': 'N21NR',
						'advancePurchase': '21',
						'bookingClass': 'N',
						'minStay': {'type': 'noRequirements'},
						'maxStay': {'type': 'noRequirements'},
						'penalties': {'type': 'complexRule'},
					},
					'2': {
						'lineNumber': 3,
						'isRoundTrip': true,
						'airline': 'B6',
						'fare': '338.00',
						'fareBasis': 'SH2QBEN5',
						'advancePurchase': '21',
						'bookingClass': 'S',
					},
					'45': {'penalties': {'type': 'nonRefundable'}},
				},
			}
		]);
		$list.push([
			php.implode(php.PHP_EOL, [
				'FARES LAST UPDATED 07JUN  9:10 AM                              ',
				'>$D15JUNBOSLAS:RT-JCB                                                    BOS-LAS DEPART 15JUN                                  ',
				'PRIVATE FARES FOR 2E8R                                         ',
				'U.S. PASSENGER FACILITY CHARGES / SURCHARGES MAY APPLY         ',
				'TAXES AND FEES MAY VARY DEPENDING ON THE BOOKED ITINERARY      ',
				'        USD     FARE         MIN/   XL  TVL DATES    TKT DATES ',
				'    CX  FARE    BASIS    AP    MAX  FE  FIRST/LAST   FIRST/LAST',
				'  1-AS  366.17R TSF01    ||  02/30  ||     -/27SEPC     -/-    ',
				'    PTC: JCB                                                   ',
				'  2-AS  452.65R GSF01    ||  02/30  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'  3-AS  574.07R TSF01    ||  02/30  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'  4-AS  577.75R KSF01    ||  02/30  ||     -/05AUGC     -/-    ',
				'    PTC: JCB                                                   ',
				'  5-AS  585.11R KSF01    ||  02/30  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'  6-AS  588.79R TSF01    ||  02/30  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'  7-AS  605.36R TSF01    ||  02/30  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'  8-AS  605.36R VSF300   ||  02/30  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'  9-AS  614.57R VSF01    ||  02/30  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				' 10-AS  656.88R LSF300   ||  02/30  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				' 11-AS  741.50R QSF300   ||  02/30  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				' 12-SY  812.00R ZT         | --/--  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'    TD:UP                                                      ',
				' 13-SY  812.00R ZT14     14| --/--  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'    TD:UP                                                      ',
				' 14-SY  812.00R ZT7      07| --/--  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'    TD:UP                                                      ',
				' 15-AS  926.00R HSF300   ||  02/30  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				' 16-SY 1013.98R VT14     14| --/--  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'    TD:UP                                                      ',
				' 17-AS 1056.00R MSF300   ||  02/30  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				' 18-SY 1074.00R WT14     14| --/--  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'    TD:UP                                                      ',
				' 19-SY 1138.00R ST7      07| --/--  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'    TD:UP                                                      ',
				' 20-AS 1208.00R BSF300   ||  02/30  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				' 21-SY 1258.00R QT7      07| --/--  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'    TD:UP                                                      ',
				' 22-SY 1368.00R HT         | --/--  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'    TD:UP                                                      ',
				' 23-AS 1400.00R SSF300   ||  02/30  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				' 24-SY 1508.00R IT         | --/--  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'    TD:UP                                                      ',
				' 25-AS 1634.00R YSF300   ||  02/30  --     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				' 26-SY 1668.00R MT         | --/--  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'    TD:UP                                                      ',
				' 27-SY 1818.00R BT         | --/--  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'    TD:UP                                                      ',
				' 28-AS 1928.00R PSF300   ||  02/30  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				' 29-SY 2118.00R YT         | --/--  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'    TD:UP                                                      ',
				' 30-AS 2148.10R FSF300   ||  02/30  --     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				' 31-SY 2202.00R Y0         | --/--  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'    TD:UP                                                      ',
				' 32-AS14642.00R YSF300   ||  02/30  --     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				' 33-SY15188.00R Y          | --/--  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'    TD:UP                                                      ',
				' 34-AS15296.00R YSF300   ||  02/30  --     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				' 35-AS18653.40R FSF300   ||  02/30  --     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				' 36-AS19411.50R FSF300   ||  02/30  --     -/-          -/-    ',
				'    PTC: JCB                                                   '
			]),
			{
				'result': {
					'0': {
						'lineNumber': 1,
						'isRoundTrip': true,
						'airline': 'AS',
						'fare': '366.17',
						'fareBasis': 'TSF01',
						'advancePurchase': '',
						'bookingClass': 'T',
					},
					'35': {
						'minStay': {'type': 'amount', 'amount': '02', 'units': 'days'},
						'maxStay': {'type': 'amount', 'amount': '30', 'units': 'days'},
						'penalties': {'type': 'noRequirements'},
					},
				},
			}
		]);
		$list.push([
			php.implode(php.PHP_EOL, [
				'FARES LAST UPDATED 15JUN  5:14 AM                              ',
				'>$D16JUNBOSLAS:RT@C::USD-JCB                                    ',
				'         BOS-LAS DEPART 16JUN                                  ',
				'PUBLIC/PRIVATE FARES FOR 2CV4                                  ',
				'U.S. PASSENGER FACILITY CHARGES / SURCHARGES MAY APPLY         ',
				'TAXES AND FEES MAY VARY DEPENDING ON THE BOOKED ITINERARY      ',
				'        USD     FARE         MIN/   XL  TVL DATES    TKT DATES ',
				'    CX  FARE    BASIS    AP    MAX  FE  FIRST/LAST   FIRST/LAST',
				'  1-SY  812.00R ZT         | --/--  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'    TD:UP                                                      ',
				'  2-SY  812.00R ZT         | --/--  ||     -/-          -/-    ',
				'    TD:UP',
				' 19-SY 1678.00R MT         | --/--  ||     -/-          -/-    ',
				'    TD:UP                                                      ',
				' 20-SY 1678.00R MT         | --/--  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'    TD:UP                                                      ',
				' 21-SY 1828.00R BT         | --/--  ||     -/-          -/-    ',
				'    TD:UP                                                      ',
				' 22-SY 1828.00R BT         | --/--  ||     -/-          -/-    ',
				'    PTC: JCB                                                   ',
				'    TD:UP                                                      ',
				' 23 SY 1838.00R CT         | --/--  --     -/-          -/-    ',
				' 24 SY 2056.00R C0         | --/--  --     -/-          -/-',
				' 30-SY15188.00R Y          | --/--  --     -/-          -/-    ',
				'    TD:UP                                                      ',
				' 31 SY17006.00R C          | --/--  --     -/-          -/-    ',
				' 32 AA19490.00R J        --  --/--  --     -/-          -/-    ',
				' 33 UA19518.00R J        --  --/--  --     -/-          -/-    ',
				' 34 DL20006.00R C          | --/--  --     -/-          -/-'
			]),
			{
				'result': {
					'8': {
						'lineNumber': 30,
						'isRoundTrip': true,
						'airline': 'SY',
						'fare': '15188.00',
						'fareBasis': 'Y',
						'advancePurchase': '',
						'bookingClass': 'Y',
					},
				},
			}
		]);
		$list.push([
			php.implode(php.PHP_EOL, [
				'FARES LAST UPDATED 16JUN  5:17 AM                              ',
				'>$D17JUNNYCLON:RT@C:USD-JCB                                     ',
				'NYC-LON FRI-17JUN16                                            ',
				'MPM 4148 AT                                                    ',
				'TAXES/FEES NOT INCLUDED                                        ',
				'PUBLIC/PRIVATE FARES FOR 2CV4                                  ',
				'     CX    FARE   FARE     C  AP  MIN/    SEASONS...... MR GI DT',
				'           USD    BASIS             MAX                        ',
				'  1  B0   918.00R VUSLDUO  V    |                       R  AT  ',
				'  9 -VS  1316.00R Z37T1U0  Z  72H  V/12M                M  AT  ',
				'     PTC: JCB ADT                                              ',
				'     TD:LN108                                                  '
			]),
			{
				'result': [
					{'ticketDesignator': null, 'ptc': []},
					{
						'lineNumber': 9,
						'isPrivateFare': true,
						'isRoundTrip': true,
						'airline': 'VS',
						'fare': '1316.00',
						'fareBasis': 'Z37T1U0',
						'bookingClass': 'Z',
						'advancePurchase': '72H',
						'isInvalid': false,
						'ticketDesignator': 'LN108',
						'ptc': ['JCB', 'ADT'],
						'isMileageBased': true,
						'oceanicFlight': {'raw': 'AT'},
					},
				],
			}
		]);
		$list.push([
			php.implode(php.PHP_EOL, [
				'FARES LAST UPDATED 17OCT  4:04 PM                              ',
				'>$D06NOVLASDAD:RT:USD-JCB                                       ',
				'LAS-DAD SUN-06NOV16                                            ',
				'MPM 9444 PA 14497 AT                                           ',
				'TAXES/FEES NOT INCLUDED                                        ',
				'PRIVATE FARES FOR 2CV4                                         ',
				'     CX    FARE   FARE     C  AP  MIN/    SEASONS...... MR GI DT',
				'           USD    BASIS             MAX                        ',
				'  1 -SQ   279.00R NSFV     N    |   /12M  01JAN -31DEC  R  PA  ',
				'     PTC: JCB                                                  ',
				'     TD:VANET                                                  ',
				'  2 -SQ   279.00R NSQV     N    |   /12M  01JAN -31DEC  R  PA D',
				'     PTC: JCB',
				'     TD:VANET                                                  ',
				'  3 -SQ   324.00R QSFV     Q    |   /12M  01JAN -31DEC  R  PA  ',
				'     PTC: JCB                                                  ',
				'     TD:VANET                                                  ',
				'  4 -SQ   324.00R QSQV     Q    |   /12M  01JAN -31DEC  R  PA D',
				'     PTC: JCB                                                  ',
				'     TD:VANET                                                  ',
				'  5 -SQ   369.00R NSFP     N    |   /12M  01JAN -31DEC  R  PA  ',
				'     PTC: JCB                                                  ',
				'     TD:VANET                                                  ',
				'  6 -SQ   369.00R NSQP     N    |   /12M  01JAN -31DEC  R  PA  ',
				'     PTC: JCB                                                  ',
				'     TD:VANET'
			]),
			{
				'success': true,
				'currency': 'USD',
				'result': {
					[0]: {
						'lineNumber': 1,
						'isPrivateFare': true,
						'isRoundTrip': true,
						'airline': 'SQ',
						'fare': '279.00',
						'seasonStart': {'parsed': '01-01', 'raw': '01JAN'},
						'seasonEnd': {'parsed': '12-31', 'raw': '31DEC'},
						'fareBasis': 'NSFV',
						'bookingClass': 'N',
						'advancePurchase': '',
						'isInvalid': false,
						'ticketDesignator': 'VANET',
					},
					[1]: {
						'lineNumber': 2,
						'hasDayRestriction': true,
						'hasTimeRestriction': false,
						'oceanicFlight': {'raw': 'PA'},
					},
					[5]: {
						'lineNumber': 6,
						'fare': '369.00',
						'ptc': ['JCB'],
						'ticketDesignator': 'VANET',
					},
				},
			}
		]);
		$list.push([
			php.implode(php.PHP_EOL, [
				'FARES LAST UPDATED 10MAY  8:11 AM                              ',
				'>$D20SEPKIVRIX                                                  KIV-RIX THU-20SEP18                                            ',
				'MPM 936 EH                                                     ',
				'TAXES/FEES NOT INCLUDED                                        ',
				'PUBLIC/PRIVATE FARES FOR 2G55                                  ',
				'USD CURRENCY FARES EXIST                                       ',
				'     CX    FARE   FARE     C  AP  MIN/    SEASONS...... MR GI DT           EUR    BASIS             MAX                        ',
				'  1  LO    28.00R OSAVO0   O    |  V/12M                R  EH  ',
				'  2  LO    48.00R USAVI0   U    |  V/12M                R  EH  ',
				'  3  TK    48.00R LN2XPB   L       V/12M                R  EH  ',
				'  4  LO    58.00R OSTDO0   O    |  V/12M                R  EH  ',
				'  5  LO    68.00R LSAVI0   L    |  V/12M                R  EH  ',
				'  6  TK    68.00R TN2XPB   T       V/12M                R  EH  ',
				'  7  LO    78.00R USTDI0   U    |  V/12M                R  EH  ',
				'  8  LH    81.00R K13LGTE4 K    |  V/12M                R  EH  ',
				'  9  LH    85.00R L13LGTE3 L    |  V/12M                R  EH  ',
				' 10  PS    91.00R N2ZEP4   N        /3M                 R  EH  ',
				' 11 /SU    95.00R NVU      N    |  V/165                R  EH  ',
				'     TD:SPL05YZSQC                                             ',
				' 12  LO    98.00R LSTDI0   L    |  V/12M                R  EH  ',
				' 13  LO    98.00R WSAVK0   W    |  V/12M                R  EH  ',
				' 14  TK    98.00R QN2PX    Q        /12M                R  EH  ',
				' 15  LH    99.00R T13LGTE3 T    |  V/12M                R  EH  ',
				' 16  SU   100.00R NVU      N    |  V/165                R  EH  ',
				')><',
			]),
			{
				'success': true,
				'currency': 'EUR',
				'result': {
					'0': {
						'lineNumber': 1,
						'airline': 'LO',
						'fare': '28.00',
						'fareBasis': 'OSAVO0',
						'maxStay': {'amount': '12', 'units': 'months'},
					},
					'10': {
						'lineNumber': 11,
						'fareType': 'agencyPrivate',
						'ticketDesignator': 'SPL05YZSQC',
						'minStay': {'type': 'complexRule'},
						'maxStay': {'type': 'amount', 'amount': '165', 'units': 'days'},
						'isRoutingBased': true,
						'isMileageBased': false,
						'oceanicFlight': {'raw': 'EH'},
						'hasDayRestriction': false,
						'hasTimeRestriction': false,
					},
				},
			}
		]);
		$list.push([
			php.implode(php.PHP_EOL, [
				'FARES LAST UPDATED 06AUG  7:20 AM                              ',
				'>$D10DECLONJFK                                                  LON-NYC MON-10DEC18                                            ',
				'MPM 4148 AT                                                    ',
				'TAXES/FEES NOT INCLUDED                                        ',
				'PUBLIC/PRIVATE FARES FOR 2G55                                  ',
				'USD EUR CURRENCY FARES EXIST                                   ',
				'     CX    FARE   FARE     C  AP  MIN/    SEASONS...... MR GI DT           GBP    BASIS             MAX                        ',
				'  1  SK     2.00R LLXEUGO  L    |  V/     25AUG -19JUN  R  AT D',
				'  2  AA     5.00R OLN2Z8B4 B  21| SU/12M  20AUG8-05JUL9 M  AT  ',
				'  3  VS     5.00R OLUR50BN T  21|  V/12M  20AUG8-05JUL9 M  AT  ',
				'  4  UA     5.00R KLO3ILGT K    |  V/3M   20AUG8-05JUL9 R  AT  ',
			]),
			{
				'header': {
					'dumpType': 'INTERNATIONAL',
					'currency': 'GBP',
					'lastUpdatedDate': {'raw': '06AUG', 'parsed': '08-06'},
					'lastUpdatedTime': {'raw': '7:20 AM', 'parsed': '07:20'},
					'commandCopy': '$D10DECLONJFK',
					'departureCity': 'LON',
					'destinationCity': 'NYC',
					'departureDayOfWeek': {'raw': 'MON'},
					'departureDate': {'raw': '10DEC18', 'parsed': '2018-12-10'},
					'unparsedLines': [
						'MPM 4148 AT',
						'TAXES/FEES NOT INCLUDED',
						'USD EUR CURRENCY FARES EXIST',
					],
					'fareSelection': 'PUBLIC/PRIVATE',
					'pcc': '2G55',
				},
				'result': [
					{'lineNumber': 1, 'airline': 'SK', 'fare': '2.00', 'fareBasis': 'LLXEUGO'},
					{'lineNumber': 2, 'airline': 'AA', 'fare': '5.00', 'fareBasis': 'OLN2Z8B4'},
					{'lineNumber': 3, 'airline': 'VS', 'fare': '5.00', 'fareBasis': 'OLUR50BN'},
					{'lineNumber': 4, 'airline': 'UA', 'fare': '5.00', 'fareBasis': 'KLO3ILGT'},
				],
			},
		]);
		$list.push([
			php.implode(php.PHP_EOL, [
				'FARES LAST UPDATED 08AUG  6:11 AM                              ',
				'>$D10AUGLAXROB                                                  ',
				'LAX-MLW FRI-10AUG18                                AIRPORT FARES',
				'MPM 8426 AT                                                    ',
				'TAXES/FEES NOT INCLUDED                                        ',
				'PUBLIC/PRIVATE FARES FOR 2G55                                  ',
				'     CX    FARE   FARE     C  AP  MIN/    SEASONS...... MR GI DT',
				'           USD    BASIS             MAX                        ',
				'LAXROB                                                         ',
				'  1 /DL   653.00R ULVL73M2 U    +  3/12M                M  AT D',
				'     TD:SSF2                                                   ',
				'  2 -SA  1927.00R WHRT2US  W    +   /12M  01JUN -10AUG  R  AT  ',
				'  3 /SA  1927.00R WHRT2US  W    +   /12M  01JUN -10AUG  R  AT  ',
				'     TD:SPL1018AJ0                                             ',
				'  4 -SA  2017.00R LHRT2US  L    +   /12M  01JUN -10AUG  R  AT  ',
				'  5 /SA  2017.00R LHRT2US  L    +   /12M  01JUN -10AUG  R  AT  ',
				'     TD:SPL1018AJ0                                             ',
				'  6 /SA  2107.00R VHRT2US  V    +   /12M  01JUN -10AUG  R  AT  ',
				'     TD:SPL1018AJ0                                             ',
				'  7  SA  2141.00R WHRT2US  W    +   /12M  01JUN -10AUG  R  AT  ',
				'  8 /SA  2215.00R THRT2US  T    +   /12M  01JUN -10AUG  R  AT  ',
				'     TD:SPL1018AJ0                                             ',
				'  9  SA  2241.00R LHRT2US  L    +   /12M  01JUN -10AUG  R  AT  ',
				' 10  SA  2341.00R VHRT2US  V    +   /12M  01JUN -10AUG  R  AT  ',
				' 11 /SA  2395.00R QHRT2US  Q    +   /12M  01JUN -10AUG  R  AT  ',
				'     TD:SPL1018AJ0                                             ',
				' 12  SA  2461.00R THRT2US  T    +   /12M  01JUN -10AUG  R  AT  ',
				' 13  SA  2661.00R QHRT2US  Q    +   /12M  01JUN -10AUG  R  AT  ',
				' 14 /SA  2692.00R SHRT2US  S    +   /12M  01JUN -10AUG  R  AT  ',
				'     TD:SPL1018AJ0                                             ',
				' 15  SA  2991.00R SHRT2US  S    +   /12M  01JUN -10AUG  R  AT  ',
				' 16 /SA  3326.00R HHRT2US  H    +   /12M  01JUN -10AUG  R  AT  ',
				'     TD:SPL1018AJ0                                             ',
				' 17  SA  3695.00R HHRT2US  H    +   /12M  01JUN -10AUG  R  AT  ',
				' 18 /SA  4267.00R KHRT2US  K    +   /12M  01JUN -10AUG  R  AT  ',
				'     TD:SPL1018AJ0                                             ',
				' 19  SA  4741.00R KHRT2US  K    +   /12M  01JUN -10AUG  R  AT  ',
				' 20 /SA  5392.00R MHRT2US  M    +   /12M  01JUN -10AUG  R  AT  ',
				'     TD:SPL1018AJ0                                             ',
				' 21  SA  5991.00R MHRT2US  M    +   /12M  01JUN -10AUG  R  AT  ',
				' 22  SA  7241.00R YRT2US   Y        /12M                R  AT  ',
				' 23  SA  4707.00  YOW2US   Y        /12M                R  AT  ',
				' 24 /SA 10166.00R JRT4     J        /12M                R  AT  ',
				'     TD:SPL1018AJ0                                             ',
				' 25  SA 11296.00R JRT4     J        /12M                R  AT  ',
				' 26 /SA 11314.00R CRT4     C        /12M                R  AT  ',
				'     TD:SPL1018AJ0                                             ',
				' 27  SA 12571.00R CRT4     C        /12M                R  AT  ',
				' 28 /SA  6397.00  JOW4     J        /12M                R  AT  ',
				'     TD:SPL1018AJ0                                             ',
				' 29 /SA  6627.00  COW4     C        /12M                R  AT  ',
				'     TD:SPL1018AJ0                                             ',
				' 30  SA  7108.00  JOW4     J        /12M                R  AT  ',
				' 31  SA  7363.00  COW4     C        /12M                R  AT  ',
				'LAXMLW                                                         ',
				' 32 /UA   133.00R KHCAX02  K  28+  7/6M                 R      ',
				'     TD:NET1VMI1FE                                             ',
				' 33 /UA   133.00R KHCAX02  K  28+  7/6M                 R      ',
				'     TD:NET1VMI1FE                                             ',
				' 34 /UA   133.00R KKCAX02  K  28+  7/6M                 R      ',
				'     TD:NET1VMI1FE                                             ',
				' 35 /UA   133.00R KKCAX02  K  28+  7/6M                 R      ',
				'     TD:NET1VMI1FE                                             ',
				' 36 /UA   133.00R KLCAX02  K  28+  7/6M                 R      ',
				'     TD:NET1VMI1FE                                             ',
				' 37 /UA   133.00R KLCAX02  K  28+  7/6M                 R      ',
				'     TD:NET1VMI1FE                                             ',
				' 38 /LH   133.00R KHCAX02  K  28+  7/6M                 R      ',
				'     TD:NET1VMI1FE                                             ',
				' 39 /LH   133.00R KHCAX02  K  28+  7/6M                 R      ',
				'     TD:NET1VMI1FE                                             ',
				' 40 /LH   133.00R KKCAX02  K  28+  7/6M                 R      ',
				'     TD:NET1VMI1FE                                             ',
				' 41 /LH   133.00R KKCAX02  K  28+  7/6M                 R      ',
				'     TD:NET1VMI1FE                                             ',
				' 42 /LH   133.00R KLCAX02  K  28+  7/6M                 R      ',
				'     TD:NET1VMI1FE                                             ',
				' 43 /LH   133.00R KLCAX02  K  28+  7/6M                 R      ',
			]),
			{
				'header': {
					'dumpType': 'INTERNATIONAL',
					'currency': 'USD',
					'lastUpdatedDate': {'raw': '08AUG', 'parsed': '08-08'},
					'lastUpdatedTime': {'raw': '6:11 AM', 'parsed': '06:11'},
					'commandCopy': '$D10AUGLAXROB',
					'departureCity': 'LAX',
					'destinationCity': 'MLW',
					'departureDayOfWeek': {'raw': 'FRI'},
					'departureDate': {'raw': '10AUG18', 'parsed': '2018-08-10'},
					'unparsedLines': ['MPM 8426 AT', 'TAXES/FEES NOT INCLUDED'],
					'fareSelection': 'PUBLIC/PRIVATE',
					'pcc': '2G55'
				},
				'result': [
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 1,
						'isRoundTrip': true,
						'airline': 'DL',
						'fare': '653.00',
						'fareBasis': 'ULVL73M2',
						'bookingClass': 'U',
						'advancePurchase': '+',
						'minStay': {'raw': '3', 'type': 'amount', 'amount': '3', 'units': 'days'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': false,
						'isMileageBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'hasDayRestriction': true,
						'ticketDesignator': 'SSF2',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 2,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '1927.00',
						'fareBasis': 'WHRT2US',
						'bookingClass': 'W',
						'advancePurchase': '+',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '01JUN', 'parsed': '06-01'},
						'seasonEnd': {'raw': '10AUG', 'parsed': '08-10'},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': null,
						'fareType': 'airlinePrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 3,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '1927.00',
						'fareBasis': 'WHRT2US',
						'bookingClass': 'W',
						'advancePurchase': '+',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '01JUN', 'parsed': '06-01'},
						'seasonEnd': {'raw': '10AUG', 'parsed': '08-10'},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': 'SPL1018AJ0',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 4,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '2017.00',
						'fareBasis': 'LHRT2US',
						'bookingClass': 'L',
						'advancePurchase': '+',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '01JUN', 'parsed': '06-01'},
						'seasonEnd': {'raw': '10AUG', 'parsed': '08-10'},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': null,
						'fareType': 'airlinePrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 5,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '2017.00',
						'fareBasis': 'LHRT2US',
						'bookingClass': 'L',
						'advancePurchase': '+',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '01JUN', 'parsed': '06-01'},
						'seasonEnd': {'raw': '10AUG', 'parsed': '08-10'},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': 'SPL1018AJ0',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 6,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '2107.00',
						'fareBasis': 'VHRT2US',
						'bookingClass': 'V',
						'advancePurchase': '+',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '01JUN', 'parsed': '06-01'},
						'seasonEnd': {'raw': '10AUG', 'parsed': '08-10'},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': 'SPL1018AJ0',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 7,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '2141.00',
						'fareBasis': 'WHRT2US',
						'bookingClass': 'W',
						'advancePurchase': '+',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '01JUN', 'parsed': '06-01'},
						'seasonEnd': {'raw': '10AUG', 'parsed': '08-10'},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': null,
						'fareType': 'public'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 8,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '2215.00',
						'fareBasis': 'THRT2US',
						'bookingClass': 'T',
						'advancePurchase': '+',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '01JUN', 'parsed': '06-01'},
						'seasonEnd': {'raw': '10AUG', 'parsed': '08-10'},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': 'SPL1018AJ0',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 9,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '2241.00',
						'fareBasis': 'LHRT2US',
						'bookingClass': 'L',
						'advancePurchase': '+',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '01JUN', 'parsed': '06-01'},
						'seasonEnd': {'raw': '10AUG', 'parsed': '08-10'},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': null,
						'fareType': 'public'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 10,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '2341.00',
						'fareBasis': 'VHRT2US',
						'bookingClass': 'V',
						'advancePurchase': '+',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '01JUN', 'parsed': '06-01'},
						'seasonEnd': {'raw': '10AUG', 'parsed': '08-10'},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': null,
						'fareType': 'public'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 11,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '2395.00',
						'fareBasis': 'QHRT2US',
						'bookingClass': 'Q',
						'advancePurchase': '+',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '01JUN', 'parsed': '06-01'},
						'seasonEnd': {'raw': '10AUG', 'parsed': '08-10'},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': 'SPL1018AJ0',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 12,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '2461.00',
						'fareBasis': 'THRT2US',
						'bookingClass': 'T',
						'advancePurchase': '+',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '01JUN', 'parsed': '06-01'},
						'seasonEnd': {'raw': '10AUG', 'parsed': '08-10'},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': null,
						'fareType': 'public'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 13,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '2661.00',
						'fareBasis': 'QHRT2US',
						'bookingClass': 'Q',
						'advancePurchase': '+',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '01JUN', 'parsed': '06-01'},
						'seasonEnd': {'raw': '10AUG', 'parsed': '08-10'},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': null,
						'fareType': 'public'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 14,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '2692.00',
						'fareBasis': 'SHRT2US',
						'bookingClass': 'S',
						'advancePurchase': '+',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '01JUN', 'parsed': '06-01'},
						'seasonEnd': {'raw': '10AUG', 'parsed': '08-10'},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': 'SPL1018AJ0',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 15,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '2991.00',
						'fareBasis': 'SHRT2US',
						'bookingClass': 'S',
						'advancePurchase': '+',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '01JUN', 'parsed': '06-01'},
						'seasonEnd': {'raw': '10AUG', 'parsed': '08-10'},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': null,
						'fareType': 'public'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 16,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '3326.00',
						'fareBasis': 'HHRT2US',
						'bookingClass': 'H',
						'advancePurchase': '+',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '01JUN', 'parsed': '06-01'},
						'seasonEnd': {'raw': '10AUG', 'parsed': '08-10'},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': 'SPL1018AJ0',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 17,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '3695.00',
						'fareBasis': 'HHRT2US',
						'bookingClass': 'H',
						'advancePurchase': '+',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '01JUN', 'parsed': '06-01'},
						'seasonEnd': {'raw': '10AUG', 'parsed': '08-10'},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': null,
						'fareType': 'public'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 18,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '4267.00',
						'fareBasis': 'KHRT2US',
						'bookingClass': 'K',
						'advancePurchase': '+',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '01JUN', 'parsed': '06-01'},
						'seasonEnd': {'raw': '10AUG', 'parsed': '08-10'},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': 'SPL1018AJ0',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 19,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '4741.00',
						'fareBasis': 'KHRT2US',
						'bookingClass': 'K',
						'advancePurchase': '+',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '01JUN', 'parsed': '06-01'},
						'seasonEnd': {'raw': '10AUG', 'parsed': '08-10'},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': null,
						'fareType': 'public'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 20,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '5392.00',
						'fareBasis': 'MHRT2US',
						'bookingClass': 'M',
						'advancePurchase': '+',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '01JUN', 'parsed': '06-01'},
						'seasonEnd': {'raw': '10AUG', 'parsed': '08-10'},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': 'SPL1018AJ0',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 21,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '5991.00',
						'fareBasis': 'MHRT2US',
						'bookingClass': 'M',
						'advancePurchase': '+',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '01JUN', 'parsed': '06-01'},
						'seasonEnd': {'raw': '10AUG', 'parsed': '08-10'},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': null,
						'fareType': 'public'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 22,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '7241.00',
						'fareBasis': 'YRT2US',
						'bookingClass': 'Y',
						'advancePurchase': '',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': null,
						'fareType': 'public'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 23,
						'isRoundTrip': false,
						'airline': 'SA',
						'fare': '4707.00',
						'fareBasis': 'YOW2US',
						'bookingClass': 'Y',
						'advancePurchase': '',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': null,
						'fareType': 'public'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 24,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '10166.00',
						'fareBasis': 'JRT4',
						'bookingClass': 'J',
						'advancePurchase': '',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': 'SPL1018AJ0',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 25,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '11296.00',
						'fareBasis': 'JRT4',
						'bookingClass': 'J',
						'advancePurchase': '',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': null,
						'fareType': 'public'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 26,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '11314.00',
						'fareBasis': 'CRT4',
						'bookingClass': 'C',
						'advancePurchase': '',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': 'SPL1018AJ0',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 27,
						'isRoundTrip': true,
						'airline': 'SA',
						'fare': '12571.00',
						'fareBasis': 'CRT4',
						'bookingClass': 'C',
						'advancePurchase': '',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': null,
						'fareType': 'public'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 28,
						'isRoundTrip': false,
						'airline': 'SA',
						'fare': '6397.00',
						'fareBasis': 'JOW4',
						'bookingClass': 'J',
						'advancePurchase': '',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': 'SPL1018AJ0',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 29,
						'isRoundTrip': false,
						'airline': 'SA',
						'fare': '6627.00',
						'fareBasis': 'COW4',
						'bookingClass': 'C',
						'advancePurchase': '',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': 'SPL1018AJ0',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 30,
						'isRoundTrip': false,
						'airline': 'SA',
						'fare': '7108.00',
						'fareBasis': 'JOW4',
						'bookingClass': 'J',
						'advancePurchase': '',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': null,
						'fareType': 'public'
					},
					{
						'departure': 'LAX',
						'destination': 'ROB',
						'lineNumber': 31,
						'isRoundTrip': false,
						'airline': 'SA',
						'fare': '7363.00',
						'fareBasis': 'COW4',
						'bookingClass': 'C',
						'advancePurchase': '',
						'minStay': {'raw': '', 'type': 'noRequirements'},
						'maxStay': {'raw': '12M', 'type': 'amount', 'amount': '12', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': 'AT'},
						'ticketDesignator': null,
						'fareType': 'public'
					},
					{
						'departure': 'LAX',
						'destination': 'MLW',
						'lineNumber': 32,
						'isRoundTrip': true,
						'airline': 'UA',
						'fare': '133.00',
						'fareBasis': 'KHCAX02',
						'bookingClass': 'K',
						'advancePurchase': '28+',
						'minStay': {'raw': '7', 'type': 'amount', 'amount': '7', 'units': 'days'},
						'maxStay': {'raw': '6M', 'type': 'amount', 'amount': '6', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': ''},
						'ticketDesignator': 'NET1VMI1FE',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'MLW',
						'lineNumber': 33,
						'isRoundTrip': true,
						'airline': 'UA',
						'fare': '133.00',
						'fareBasis': 'KHCAX02',
						'bookingClass': 'K',
						'advancePurchase': '28+',
						'minStay': {'raw': '7', 'type': 'amount', 'amount': '7', 'units': 'days'},
						'maxStay': {'raw': '6M', 'type': 'amount', 'amount': '6', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': ''},
						'ticketDesignator': 'NET1VMI1FE',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'MLW',
						'lineNumber': 34,
						'isRoundTrip': true,
						'airline': 'UA',
						'fare': '133.00',
						'fareBasis': 'KKCAX02',
						'bookingClass': 'K',
						'advancePurchase': '28+',
						'minStay': {'raw': '7', 'type': 'amount', 'amount': '7', 'units': 'days'},
						'maxStay': {'raw': '6M', 'type': 'amount', 'amount': '6', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': ''},
						'ticketDesignator': 'NET1VMI1FE',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'MLW',
						'lineNumber': 35,
						'isRoundTrip': true,
						'airline': 'UA',
						'fare': '133.00',
						'fareBasis': 'KKCAX02',
						'bookingClass': 'K',
						'advancePurchase': '28+',
						'minStay': {'raw': '7', 'type': 'amount', 'amount': '7', 'units': 'days'},
						'maxStay': {'raw': '6M', 'type': 'amount', 'amount': '6', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': ''},
						'ticketDesignator': 'NET1VMI1FE',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'MLW',
						'lineNumber': 36,
						'isRoundTrip': true,
						'airline': 'UA',
						'fare': '133.00',
						'fareBasis': 'KLCAX02',
						'bookingClass': 'K',
						'advancePurchase': '28+',
						'minStay': {'raw': '7', 'type': 'amount', 'amount': '7', 'units': 'days'},
						'maxStay': {'raw': '6M', 'type': 'amount', 'amount': '6', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': ''},
						'ticketDesignator': 'NET1VMI1FE',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'MLW',
						'lineNumber': 37,
						'isRoundTrip': true,
						'airline': 'UA',
						'fare': '133.00',
						'fareBasis': 'KLCAX02',
						'bookingClass': 'K',
						'advancePurchase': '28+',
						'minStay': {'raw': '7', 'type': 'amount', 'amount': '7', 'units': 'days'},
						'maxStay': {'raw': '6M', 'type': 'amount', 'amount': '6', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': ''},
						'ticketDesignator': 'NET1VMI1FE',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'MLW',
						'lineNumber': 38,
						'isRoundTrip': true,
						'airline': 'LH',
						'fare': '133.00',
						'fareBasis': 'KHCAX02',
						'bookingClass': 'K',
						'advancePurchase': '28+',
						'minStay': {'raw': '7', 'type': 'amount', 'amount': '7', 'units': 'days'},
						'maxStay': {'raw': '6M', 'type': 'amount', 'amount': '6', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': ''},
						'ticketDesignator': 'NET1VMI1FE',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'MLW',
						'lineNumber': 39,
						'isRoundTrip': true,
						'airline': 'LH',
						'fare': '133.00',
						'fareBasis': 'KHCAX02',
						'bookingClass': 'K',
						'advancePurchase': '28+',
						'minStay': {'raw': '7', 'type': 'amount', 'amount': '7', 'units': 'days'},
						'maxStay': {'raw': '6M', 'type': 'amount', 'amount': '6', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': ''},
						'ticketDesignator': 'NET1VMI1FE',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'MLW',
						'lineNumber': 40,
						'isRoundTrip': true,
						'airline': 'LH',
						'fare': '133.00',
						'fareBasis': 'KKCAX02',
						'bookingClass': 'K',
						'advancePurchase': '28+',
						'minStay': {'raw': '7', 'type': 'amount', 'amount': '7', 'units': 'days'},
						'maxStay': {'raw': '6M', 'type': 'amount', 'amount': '6', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': ''},
						'ticketDesignator': 'NET1VMI1FE',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'MLW',
						'lineNumber': 41,
						'isRoundTrip': true,
						'airline': 'LH',
						'fare': '133.00',
						'fareBasis': 'KKCAX02',
						'bookingClass': 'K',
						'advancePurchase': '28+',
						'minStay': {'raw': '7', 'type': 'amount', 'amount': '7', 'units': 'days'},
						'maxStay': {'raw': '6M', 'type': 'amount', 'amount': '6', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': ''},
						'ticketDesignator': 'NET1VMI1FE',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'MLW',
						'lineNumber': 42,
						'isRoundTrip': true,
						'airline': 'LH',
						'fare': '133.00',
						'fareBasis': 'KLCAX02',
						'bookingClass': 'K',
						'advancePurchase': '28+',
						'minStay': {'raw': '7', 'type': 'amount', 'amount': '7', 'units': 'days'},
						'maxStay': {'raw': '6M', 'type': 'amount', 'amount': '6', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': ''},
						'ticketDesignator': 'NET1VMI1FE',
						'fareType': 'agencyPrivate'
					},
					{
						'departure': 'LAX',
						'destination': 'MLW',
						'lineNumber': 43,
						'isRoundTrip': true,
						'airline': 'LH',
						'fare': '133.00',
						'fareBasis': 'KLCAX02',
						'bookingClass': 'K',
						'advancePurchase': '28+',
						'minStay': {'raw': '7', 'type': 'amount', 'amount': '7', 'units': 'days'},
						'maxStay': {'raw': '6M', 'type': 'amount', 'amount': '6', 'units': 'months'},
						'seasonStart': {'raw': '', 'parsed': null},
						'seasonEnd': {'raw': '', 'parsed': null},
						'isRoutingBased': true,
						'oceanicFlight': {'raw': ''},
						'ticketDesignator': null,
						'fareType': 'agencyPrivate'
					},
				],
			},
		]);
		return $list;
	}

	/**
	 * @test
	 * @dataProvider provideTreeTestCases
	 */
	testTreeTestCase($dump, $expected) {
		let $actual;
		$actual = TariffDisplayParser.parse($dump);
		try {
			this.assertArrayElementsSubset($expected, $actual, '', true);
		} catch (exc) {
			let args = process.argv.slice(process.execArgv.length + 2);
			if (args.includes('debug')) {
				console.log('\n$actual\n', JSON.stringify($actual));
			}
			throw exc;
		}
	}

	getTestMapping() {
		return [
			[this.provideTreeTestCases, this.testTreeTestCase],
		];
	}
}

module.exports = TariffDisplayParserTest;
