before_script:
  - node --version

run-tests:
  variables:
    GIT_STRATEGY: none
  tags:
    - php70-builder # it has node v8.x at least
  only:
    - master
  environment:
      name: staging
      url: http://gds-direct-plus.gitlab-runner.php7.dyninno.net
  script:
  - git config --global user.name "Gitlab CI"
  - git config --global user.email "gitlab@dyninno.net"
#  - test -e "/home/gitlab-runner/public_html/gds-direct-plus" || git clone $CI_REPOSITORY_URL -b master /home/gitlab-runner/public_html/gds-direct-plus --depth 1
#  - cd /home/gitlab-runner/public_html/gds-direct-plus
  - export CI_PUSH_REPO=`echo $CI_REPOSITORY_URL | perl -pe 's#.*@(.+?(\:\d+)?)/#git@\1:#'`
  - git remote set-url origin "${CI_PUSH_REPO}"
  - echo ${CI_PUSH_REPO}
  - git status
  - bash build.sh
  - ls
  #- cp local.config.conf.dist local.config.conf
  #- node tests/runTests.js