stages:
- setup
- test

before_script:
  - node --version

setup:
  stage: setup
  tags:
    - dev-w04
  only:
    - master
  environment:
      name: staging
      url: http://gds-direct-plus.gitlab-runner.php7.dyninno.net
  script:
    - bash build.sh
    - cp .env.dist .env
  artifacts:
    paths:
      - node_modules/
      - public/node_modules/
    expire_in: 1 week

run-tests:
  stage: test
  script:
#  - test -e "/home/gitlab-runner/public_html/gds-direct-plus" || git clone $CI_REPOSITORY_URL -b master /home/gitlab-runner/public_html/gds-direct-plus --depth 1
#  - cd /home/gitlab-runner/public_html/gds-direct-plus
  - node_modules/node/bin/node tests/runTests.js