stages:
- test
- build

before_script:
  - node --version

run-tests:
  stage: test
  variables:
    GIT_STRATEGY: fetch
  tags:
    - php70-builder # it has node v8.x at least
  only:
    - master
  environment:
      name: staging
      url: http://gds-direct-plus.gitlab-runner.php7.dyninno.net
  script:
  - git show --name-status
  - git branch
#  - test -e "/home/gitlab-runner/public_html/gds-direct-plus" || git clone $CI_REPOSITORY_URL -b master /home/gitlab-runner/public_html/gds-direct-plus --depth 1
#  - cd /home/gitlab-runner/public_html/gds-direct-plus
#  - bash build.sh
#  - cp local.config.conf.dist local.config.conf
#  - node tests/runTests.js