stages:
- test

run-tests-dev:
  tags:
  - sales-team-runner
  except:
    - tags
    - production
  script:
    - npm ci
    - node tests/run.js

run-tests-prod:
  tags:
    - sales-team-runner
  only:
    #- tags
    - production
  script:
    - npm ci # install devDependencies
    - node tests/run.js
