stages:
- test
- build
staging:
  variables:
    GIT_STRATEGY: none
  tags:
    - php70-builder
  only:
    - master
  environment:
      name: staging
      url: http://gds-direct-plus.gitlab-runner.php7.dyninno.net
  script:
  #- rm -rf /home/gitlab-runner/public_html/cms/cache
  - . /home/pkirpitsov/scripts/ci_secret_ssh.sh
  - git config --global user.name "Gitlab CI"
  - git config --global user.email "gitlab@dyninno.net"
  - test -e "/home/gitlab-runner/public_html/gds-direct-plus" || git clone $CI_REPOSITORY_URL -b master /home/gitlab-runner/public_html/gds-direct-plus --depth 1
  - cd /home/gitlab-runner/public_html/gds-direct-plus
#  - cp local.config.php.dist local.config.php
  - export CI_PUSH_REPO=`echo $CI_REPOSITORY_URL | perl -pe 's#.*@(.+?(\:\d+)?)/#git@\1:#'`
  - git remote set-url origin "${CI_PUSH_REPO}"
  - echo ${CI_PUSH_REPO}
  - git reset --hard origin/master
  - git pull
  - bash build.sh
  - kill $SSH_AGENT_PID