stages:
- test

before_script:
  - node --version

# takes 1 minute and 9 seconds
run-tests-dev:
  before_script:
    # Set up git
    - . /home/pkirpitsov/scripts/ci_secret_ssh.sh
    - git config --global user.name "Gitlab CI"
    - git config --global user.email "gitlab@dyninno.net"
  tags:
    - dev-w13
  except:
    - tags
    - production
  script:
    - bash build.sh
    # dev-w13 has node 9.8 sadly, it has limited regex support
    - npm install node@10.13.0
    - node_modules/node/bin/node tests/runTests.js

# takes 16 seconds, could be even faster if it did not install node 10 each time...
run-tests-prod:
  tags:
    - dev-w13
  only:
    #- tags
    - production
  script:
    # dev-w13 has node 9.8 sadly, it has limited regex support
    - npm install node@10.13.0
    - node_modules/node/bin/node tests/runTests.js
