


const FareRuleOrSegmentsParser = require('../../../../../../backend/Transpiled/Gds/Parsers/Sabre/FareRuleOrSegmentsParser.js');

const php = require('klesun-node-tools/src/Transpiled/php.js');
class FareRuleOrSegmentsParserTest extends require('klesun-node-tools/src/Transpiled/Lib/TestCase.js')
{
	provideDumps()  {
		let $list;

		$list = [];

		$list.push([
			php.implode(php.PHP_EOL, [
				'MULTIPLE RULE CONDITIONS - SEGMENT SELECT. SEE WPRDHELP',
				' ',
				'SEG  CTYPAIR  FQ       RULE   CXR  PU   FARE      FAREBASIS ',
				'01   JFKLOS   NYCLOS   2610   W3   01   116.50    VKRT6MUS',
				'02   LOSJFK   NYCLOS   2810   W3   01   111.50    XKRT3MUS',
				'.',
			]),
			{
				'type': 'segmentList',
				'data': [
					{'segmentNumber': '01', 'destinationAirport': 'LOS', 'fareBasis': 'VKRT6MUS'},
					{'segmentNumber': '02', 'destinationAirport': 'JFK', 'fareBasis': 'XKRT3MUS'},
				],
			},
		]);

		$list.push([
			php.implode(php.PHP_EOL, [
				'    V FARE BASIS     BK    FARE   TRAVEL-TICKET AP  MINMAX  RTG',
				'  1 . QEEIF3M        Q R  3500.00     ----      -    4/ 3M EH01',
				'PASSENGER TYPE-ADT                 AUTO PRICE-YES              ',
				'FROM-LOS TO-MLW    CXR-YY    TVL-03OCT16  RULE-AFEX 031SITA/31',
				'FARE BASIS-YEEIF3M           SPECIAL FARE  DIS-E   VENDOR-SITA',
				'FARE TYPE-XEX      RT-REGULAR EXCURSION',
				'TARIFF FAMILY-J    DBE-YE     FARE QUALITY-E    ROUTE CODE-42',
				'USD  3500.00   MPM  E11FEB16 D-INFINITY   FC-YEEIF3M  FN-16   ',
				'SYSTEM DATES - CREATED 07FEB16/1130  EXPIRES INFINITY',
				' ',
				'50.RULE APPLICATION AND OTHER CONDITIONS',
				'   NOTE - THE FOLLOWING TEXT IS INFORMATIONAL AND NOT',
				'   VALIDATED FOR AUTOPRICING.',
				'   EXCURSION FLEX FARES WITHIN AFRICA',
				'   APPLICATION',
				'    AREA',
				'     THESE FARES APPLY WITHIN AFRICA.',
				'    CLASS OF SERVICE',
				'     THESE FARES APPLY FOR ECONOMY CLASS SERVICE.',
				'    TYPES OF TRANSPORTATION',
				'     THIS RULE GOVERNS ROUND-TRIP FARES.',
				'     FARES GOVERNED BY THIS RULE CAN BE USED TO CREATE',
				'      ROUND-TRIP/CIRCLE-TRIP/OPEN-JAW JOURNEYS.',
				'    OTHER CONDITIONS',
				'     EXCEPT WITHIN EASTERN AFRICA.',
				'     FARES ONLY APPLY IF PURCHASED BEFORE DEPARTURE.',
				'     EXCEPTION -',
				'     MAY BE USED FOR ENROUTE UPGRADING FROM A LOWER',
				'     FARE PROVIDED ALL CONDITIONS OF THESE FARES ARE',
				'     MET.',
				'     PASSENGER EXPENSES NOT PERMITTED.',
				'01.ELIGIBILITY',
				'         NOTE - TEXT BELOW NOT VALIDATED FOR AUTOPRICING.',
				'          UNACCOMPAINED INFANT- NOT ELIGIBLE',
				'02.DAY/TIME',
				'   NO DAY/TIME TRAVEL RESTRICTIONS APPLY.',
				'03.SEASONALITY',
				'   NO SEASONAL TRAVEL RESTRICTIONS APPLY.',
				'04.FLIGHT APPLICATION',
				'   NO FLIGHT RESTRICTIONS APPLY.',
				'05.ADVANCE RESERVATIONS/TICKETING',
				'   NO ADVANCE RESERVATIONS/TICKETING REQUIREMENTS APPLY.',
				'06.MINIMUM STAY',
				'   TRAVEL FROM DEPARTURE FROM LAST STOPOVER OUTSIDE',
				'   GEOGRAPHIC TYPE OF FARE ORIGIN MUST COMMENCE NO',
				'   EARLIER THAN 4 DAYS AFTER DEPARTURE OF THE FIRST',
				'   INTERNATIONAL SECTOR.',
				'         NOTE - TEXT BELOW NOT VALIDATED FOR AUTOPRICING.',
				'          WAIVER OF MINIMUM STAY -',
				'          AFTER TICKET ISSUANCE - PERMITTED ONLY IN THE',
				'          EVENT OF DEATH OF AN IMMEDIATE FAMILY MEMBER',
				'          OR AN ACCOMPANYING PASSENGER.',
				'07.MAXIMUM STAY',
				'   TRAVEL FROM LAST STOPOVER MUST COMMENCE NO LATER THAN',
				'   3 MONTHS AFTER DEPARTURE FROM FARE ORIGIN.',
				'08.STOPOVERS',
				'   2 FREE STOPOVERS PERMITTED ON THE PRICING UNIT - 1 IN',
				'   EACH DIRECTION.',
				'09.TRANSFERS',
				'   2 TRANSFERS PERMITTED IN EACH DIRECTION.',
				'   FARE BREAK AND EMBEDDED SURFACE SECTORS PERMITTED ON',
				'   THE FARE COMPONENT.',
				'10.COMBINATIONS',
				'    ',
				'    FARES MAY BE COMBINED ON A HALF ROUND TRIP BASIS WITH',
				'    ANY FARE FOR ANY CARRIER IN ANY RULE AND TARIFF TO',
				'    FORM SINGLE/DOUBLE OPEN JAWS/ROUND TRIPS/CIRCLE',
				'    TRIPS.',
				'   END-ON-END',
				'     END-ON-END COMBINATIONS PERMITTED. VALIDATE ALL FARE',
				'     COMPONENTS. SIDE TRIPS PERMITTED WITH NO',
				'     RESTRICTIONS.',
				'     END-ON-END NOTE -',
				'       END-ON AND SIDE TRIP COMBINATIONS PERMITTED',
				'       IN THE CASE OF SIDE TRIPS. SUCH SIDE TRIPS ARE',
				'       ONLY PERMITTED FROM AND TO THE SAME ENROUTE',
				'       POINT OF A FARE COMPONENT.',
				'11.BLACKOUT DATES',
				'   NO BLACKOUT DATES APPLY.',
				'12.SURCHARGES',
				'   NO SURCHARGE REQUIREMENTS APPLY.',
				'13.ACCOMPANIED TRAVEL',
				'   ACCOMPANIED TRAVEL NOT REQUIRED.',
				'14.TRAVEL RESTRICTIONS',
				'   VALID FOR TRAVEL COMMENCING ON/AFTER 11FEB16.',
				'15.SALES RESTRICTIONS',
				'   FOOTNOTE RULE',
				'   TICKETS MUST BE ISSUED ON/AFTER 11FEB16.',
				' ',
				'   GENERAL RULE - APPLY UNLESS OTHERWISE SPECIFIED',
				'         NOTE - TEXT BELOW NOT VALIDATED FOR AUTOPRICING.',
				'          -ADVERTISING AND SALES - NO RESTRICTIONS.',
				'          -SALES -',
				'           SHALL INCLUDE THE ISSUANCE OF TICKETS AND',
				'           ELECTRONIC MISCELLANEOUS DOCUMENT -EMDS-',
				'          -ADVERTISING -',
				'           ANY LIMITATIONS ON ADVERTISING SHALL NOT',
				'           PRECLUDE THE QUOTING OF SUCH FARES IN COMPANY',
				'           TARIFFS AND SYSTEM TIMETABLES AND AIR GUIDES.',
				'           EXTENSION OF VALIDITY -',
				'           A CARRIER MAY WITHOUT ADDITIONAL COLLECTION OF',
				'           FARE EXTEND THE VALIDITY OF THE TICKET OF A',
				'           PASSENGER WHO IS PREVENTED FROM TRAVELLING',
				'           WITHIN THE PERIOD OF VALIDITY OF HIS TICKET.',
				'16.PENALTIES',
				'   NO PENALTIES APPLY.',
				'17.HIP/MILEAGE EXCEPTIONS',
				'   NO HIP OR MILEAGE EXCEPTIONS APPLY.',
				'18.TICKET ENDORSEMENTS',
				'   TICKET ENDORSEMENT NOT REQUIRED.',
				'19.CHILDREN DISCOUNTS',
				'   FARE RULE',
				'   CNN/ACCOMPANIED CHILD PSGR 2-11 - CHARGE 75 PERCENT OF',
				'     THE FARE.',
				'         TICKET DESIGNATOR - CH AND PERCENT APPLIED.',
				'     MUST BE ACCOMPANIED ON ALL FLIGHTS BY ADULT PSGR 12',
				'       OR OLDER.',
				'   OR - UNN/UNACCOMPANIED CHILD PSGR 2-11 - CHARGE 100',
				'          PERCENT OF THE FARE.',
				'         NOTE - TEXT BELOW NOT VALIDATED FOR AUTOPRICING.',
				'          ON SERVICES OF KQ/IR/TM- CHILDREN UNDER THE AGE',
				'          OF 5 NOT PERMITTED',
				'   OR - 1ST INF/INFANT WITHOUT A SEAT PSGR UNDER 2 -',
				'          CHARGE 10 PERCENT OF THE FARE.',
				'              TICKET DESIGNATOR - IN AND PERCENT APPLIED.',
				'          MUST BE ACCOMPANIED ON ALL FLIGHTS BY ADULT PSGR',
				'            12 OR OLDER.',
				'   OR - INS/INFANT WITH A SEAT PSGR UNDER 2 - CHARGE 75',
				'          PERCENT OF THE FARE.',
				'              TICKET DESIGNATOR - CH AND PERCENT APPLIED.',
				'          MUST BE ACCOMPANIED ON ALL FLIGHTS BY ADULT PSGR',
				'            12 OR OLDER.',
				' ',
				'   GENERAL RULE - APPLY UNLESS OTHERWISE SPECIFIED',
				'   CNN/ACCOMPANIED CHILD PSGR 2-11 - CHARGE 75 PERCENT OF',
				'     THE FARE.',
				'         TICKET DESIGNATOR - CH AND PERCENT APPLIED.',
				'     MUST BE ACCOMPANIED ON ALL FLIGHTS BY ADULT PSGR 12',
				'       OR OLDER.',
				'   OR - UNN/UNACCOMPANIED CHILD PSGR 2-11 - CHARGE 100',
				'          PERCENT OF THE FARE.',
				'              TICKET DESIGNATOR - CH AND PERCENT APPLIED.',
				'   OR - INF/INFANT WITHOUT A SEAT PSGR UNDER 2 - CHARGE 10',
				'          PERCENT OF THE FARE.',
				'              TICKET DESIGNATOR - IN AND PERCENT APPLIED.',
				'          MUST BE ACCOMPANIED ON ALL FLIGHTS BY AT LEAST 1',
				'            BUT NO MORE THAN 1 ADULT PSGR 12 OR OLDER.',
				'   OR - INS/INFANT WITH A SEAT PSGR UNDER 2 - CHARGE 75',
				'          PERCENT OF THE FARE.',
				'              TICKET DESIGNATOR - CH AND PERCENT APPLIED.',
				'          MUST BE ACCOMPANIED ON ALL FLIGHTS BY ADULT PSGR',
				'            12 OR OLDER.',
				'   OR - ',
				'         NOTE - TEXT BELOW NOT VALIDATED FOR AUTOPRICING.',
				'          UNACCOMPANIED INFANT NOT PERMITTED.',
				'          EXCEPTION - UNACCOMPANIED INFANTS MAY BE ACCEPTED',
				'          FOR TRANSPORTATION PROVIDED PRIOR ARRANGEMENTS',
				'          HAVE BEEN MADE WITH THE TRANSPORTING CARRIER OR',
				'          CARRIERS. THE CHARGE SHALL BE BE 100 PERCENT OF',
				'          THE APPLICABLE ADULT FARE.',
				'20.TOUR CONDUCTOR DISCOUNTS',
				'   NO DISCOUNTS FOR TOUR CONDUCTORS.',
				'21.AGENT DISCOUNTS',
				'   NO DISCOUNTS FOR SALE AGENTS.',
				'22.ALL OTHER DISCOUNTS',
				'         NOTE - TEXT BELOW NOT VALIDATED FOR AUTOPRICING.',
				'          PERMITTED',
				'23.MISCELLANEOUS PROVISIONS',
				'   NO PROVISIONS APPLY.',
				'25.FARE BY RULE',
				'   NOT APPLICABLE.',
				'26.GROUPS',
				'   NO GROUP PROVISIONS APPLY.',
				'27.TOURS',
				'   NO TOUR PROVISIONS APPLY.',
				'28.VISIT ANOTHER COUNTRY',
				'   NO VISIT ANOTHER COUNTRY PROVISIONS APPLY.',
				'29.DEPOSITS',
				'   NO DEPOSIT PROVISIONS APPLY.',
				'31.VOLUNTARY CHANGES',
				'   NO VOLUNTARY CHANGES DATA FOUND.',
				'33.VOLUNTARY REFUNDS',
				'   NO VOLUNTARY REFUNDS DATA FOUND.',
				'35.NEGOTIATED FARES',
				'   NOT APPLICABLE.',
				'IC.INTERNATIONAL CONSTRUCTION',
				'   NOT A CONSTRUCTED FARE',
				'.',
			]),
			{
				'type': 'singleRule',
				'data': {
					'fareComponent': {
						'vendorCode': '.',
						'fareBasis': 'QEEIF3M',
						'primaryBookingClass': 'Q',
						'tripType': {'parsed': 'roundTrip'},
						'fare': '3500.00',
						'stayMin': {'parsed': {'type': 'amount', 'amount': '4', 'units': 'days'}},
						'stayMax': {'parsed': {'type': 'amount', 'amount': '3', 'units': 'months'}},
					},
					'header': {
						'ptc': 'ADT',
						'autoPriceFlag': 'YES',
						'departureCity': 'LOS',
						'destinationCity': 'MLW',
						'airline': 'YY',
						'travelDate': {'parsed': '2016-10-03'},
						'rule': 'AFEX 031SITA/31',
						'fareBasis': 'YEEIF3M',
						'fareSpecialization': 'SPECIAL',
						'dis': 'E',
						'vendor': 'SITA',
						'fareType': 'XEX',
						'tripType': 'RT',
						'tripTypeRemark': 'REGULAR EXCURSION',
						'tariffFamily': 'J',
						'dbe': 'YE',
						'fareQuality': 'E',
						'routeCode': '42',
						'currency': 'USD',
						'amount': '3500.00',
						'mileagePoints': 'MPM',
						'effectiveDateForOutboundTravel': {'parsed': '2016-02-11'},
						'discontinueDateForOutboundTravel': {'raw': 'INFINITY'},
						'fareConstructionBasis': 'YEEIF3M',
						'fareNumber': '16',
						'createdDate': {'parsed': '2016-02-07'},
						'createdTime': {'parsed': '11:30'},
						'expiresDate': 'INFINITY',
					},
				},
			},
		]);

		return $list;
	}

	/**
     * @test
     * @dataProvider provideDumps
     */
	testParser($dump, $expectedResult)  {
		let $actualResult;

		$actualResult = FareRuleOrSegmentsParser.parse($dump);
		this.assertArrayElementsSubset($expectedResult, $actualResult);
	}

	getTestMapping() {
		return [
			[this.provideDumps, this.testParser],
		];
	}
}
FareRuleOrSegmentsParserTest.count = 0;
module.exports = FareRuleOrSegmentsParserTest;
