interface IIoRedisClient {
	append: (...args) => Promise<any>,
	auth: (...args) => Promise<any>,
	bgrewriteaof: (...args) => Promise<any>,
	bgsave: (...args) => Promise<any>,
	bitcount: (...args) => Promise<any>,
	bitfield: (...args) => Promise<any>,
	bitop: (...args) => Promise<any>,
	bitpos: (...args) => Promise<any>,
	blpop: (...args) => Promise<any>,
	brpop: (...args) => Promise<any>,
	brpoplpush: (...args) => Promise<any>,
	bzpopmin: (...args) => Promise<any>,
	bzpopmax: (...args) => Promise<any>,
	dbsize: (...args) => Promise<any>,
	decr: (...args) => Promise<any>,
	decrby: (...args) => Promise<any>,
	del: (...args) => Promise<any>,
	discard: (...args) => Promise<any>,
	dump: (...args) => Promise<any>,
	echo: (...args) => Promise<any>,
	eval: (...args) => Promise<any>,
	evalsha: (...args) => Promise<any>,
	exec: (...args) => Promise<any>,
	exists: (...args) => Promise<any>,
	expire: (...args) => Promise<any>,
	expireat: (...args) => Promise<any>,
	flushall: (...args) => Promise<any>,
	flushdb: (...args) => Promise<any>,
	geoadd: (...args) => Promise<any>,
	geohash: (...args) => Promise<any>,
	geopos: (...args) => Promise<any>,
	geodist: (...args) => Promise<any>,
	georadius: (...args) => Promise<any>,
	georadiusbymember: (...args) => Promise<any>,
	get: (...args) => Promise<any>,
	getbit: (...args) => Promise<any>,
	getrange: (...args) => Promise<any>,
	getset: (...args) => Promise<any>,
	hdel: (...args) => Promise<any>,
	hexists: (...args) => Promise<any>,
	hget: (...args) => Promise<any>,
	hgetall: (...args) => Promise<any>,
	hincrby: (...args) => Promise<any>,
	hincrbyfloat: (...args) => Promise<any>,
	hkeys: (...args) => Promise<any>,
	hlen: (...args) => Promise<any>,
	hmget: (...args) => Promise<any>,
	hmset: (...args) => Promise<any>,
	hset: (...args) => Promise<any>,
	hsetnx: (...args) => Promise<any>,
	hstrlen: (...args) => Promise<any>,
	hvals: (...args) => Promise<any>,
	incr: (...args) => Promise<any>,
	incrby: (...args) => Promise<any>,
	incrbyfloat: (...args) => Promise<any>,
	info: (...args) => Promise<any>,
	keys: (...args) => Promise<any>,
	lastsave: (...args) => Promise<any>,
	lindex: (...args) => Promise<any>,
	linsert: (...args) => Promise<any>,
	llen: (...args) => Promise<any>,
	lpop: (...args) => Promise<any>,
	lpush: (...args) => Promise<any>,
	lpushx: (...args) => Promise<any>,
	lrange: (...args) => Promise<any>,
	lrem: (...args) => Promise<any>,
	lset: (...args) => Promise<any>,
	ltrim: (...args) => Promise<any>,
	mget: (...args) => Promise<any>,
	migrate: (...args) => Promise<any>,
	monitor: (...args) => Promise<any>,
	move: (...args) => Promise<any>,
	mset: (...args) => Promise<any>,
	msetnx: (...args) => Promise<any>,
	multi: (...args) => Promise<any>,
	object: (...args) => Promise<any>,
	persist: (...args) => Promise<any>,
	pexpire: (...args) => Promise<any>,
	pexpireat: (...args) => Promise<any>,
	pfadd: (...args) => Promise<any>,
	pfcount: (...args) => Promise<any>,
	pfmerge: (...args) => Promise<any>,
	ping: (...args) => Promise<any>,
	psetex: (...args) => Promise<any>,
	psubscribe: (...args) => Promise<any>,
	pubsub: (...args) => Promise<any>,
	pttl: (...args) => Promise<any>,
	publish: (...args) => Promise<any>,
	punsubscribe: (...args) => Promise<any>,
	quit: (...args) => Promise<any>,
	randomkey: (...args) => Promise<any>,
	readonly: (...args) => Promise<any>,
	readwrite: (...args) => Promise<any>,
	rename: (...args) => Promise<any>,
	renamenx: (...args) => Promise<any>,
	restore: (...args) => Promise<any>,
	role: (...args) => Promise<any>,
	rpop: (...args) => Promise<any>,
	rpoplpush: (...args) => Promise<any>,
	rpush: (...args) => Promise<any>,
	rpushx: (...args) => Promise<any>,
	sadd: (...args) => Promise<any>,
	save: (...args) => Promise<any>,
	scard: (...args) => Promise<any>,
	sdiff: (...args) => Promise<any>,
	sdiffstore: (...args) => Promise<any>,
	select: (...args) => Promise<any>,
	set: (...args) => Promise<any>,
	setbit: (...args) => Promise<any>,
	setex: (...args) => Promise<any>,
	setnx: (...args) => Promise<any>,
	setrange: (...args) => Promise<any>,
	shutdown: (...args) => Promise<any>,
	sinter: (...args) => Promise<any>,
	sinterstore: (...args) => Promise<any>,
	sismember: (...args) => Promise<any>,
	slaveof: (...args) => Promise<any>,
	replicaof: (...args) => Promise<any>,
	slowlog: (...args) => Promise<any>,
	smembers: (...args) => Promise<any>,
	smove: (...args) => Promise<any>,
	sort: (...args) => Promise<any>,
	spop: (...args) => Promise<any>,
	srandmember: (...args) => Promise<any>,
	srem: (...args) => Promise<any>,
	strlen: (...args) => Promise<any>,
	subscribe: (...args) => Promise<any>,
	sunion: (...args) => Promise<any>,
	sunionstore: (...args) => Promise<any>,
	swapdb: (...args) => Promise<any>,
	sync: (...args) => Promise<any>,
	time: (...args) => Promise<any>,
	touch: (...args) => Promise<any>,
	ttl: (...args) => Promise<any>,
	type: (...args) => Promise<any>,
	unsubscribe: (...args) => Promise<any>,
	unlink: (...args) => Promise<any>,
	unwatch: (...args) => Promise<any>,
	wait: (...args) => Promise<any>,
	watch: (...args) => Promise<any>,
	zadd: (...args) => Promise<any>,
	zcard: (...args) => Promise<any>,
	zcount: (...args) => Promise<any>,
	zincrby: (...args) => Promise<any>,
	zinterstore: (...args) => Promise<any>,
	zlexcount: (...args) => Promise<any>,
	zpopmax: (...args) => Promise<any>,
	zpopmin: (...args) => Promise<any>,
	zrange: (...args) => Promise<any>,
	zrangebylex: (...args) => Promise<any>,
	zrevrangebylex: (...args) => Promise<any>,
	zrangebyscore: (...args) => Promise<any>,
	zrank: (...args) => Promise<any>,
	zrem: (...args) => Promise<any>,
	zremrangebylex: (...args) => Promise<any>,
	zremrangebyrank: (...args) => Promise<any>,
	zremrangebyscore: (...args) => Promise<any>,
	zrevrange: (...args) => Promise<any>,
	zrevrangebyscore: (...args) => Promise<any>,
	zrevrank: (...args) => Promise<any>,
	zscore: (...args) => Promise<any>,
	zunionstore: (...args) => Promise<any>,
	scan: (...args) => Promise<any>,
	sscan: (...args) => Promise<any>,
	hscan: (...args) => Promise<any>,
	zscan: (...args) => Promise<any>,
	xinfo: (...args) => Promise<any>,
	xadd: (...args) => Promise<any>,
	xtrim: (...args) => Promise<any>,
	xdel: (...args) => Promise<any>,
	xrange: (...args) => Promise<any>,
	xrevrange: (...args) => Promise<any>,
	xlen: (...args) => Promise<any>,
	xread: (...args) => Promise<any>,
	xgroup: (...args) => Promise<any>,
	xreadgroup: (...args) => Promise<any>,
	xack: (...args) => Promise<any>,
	xclaim: (...args) => Promise<any>,
	xpending: (...args) => Promise<any>,
}

interface IRedisInfo {
    // Server
	"redis_version": "3.0.6",
	"redis_git_sha1": "00000000",
	"redis_git_dirty": "0",
	"redis_build_id": "28b6715d3583bf8e",
	"redis_mode": "standalone",
	"os": "Linux 4.4.0-124-generic x86_64",
	"arch_bits": "64",
	"multiplexing_api": "epoll",
	"gcc_version": "5.4.0",
	"process_id": "31643",
	"run_id": "5d6f271fefe3edcaa770d4a6b7bbe2d204ffcd1d",
	"tcp_port": "6379",
	"uptime_in_seconds": "3567459",
	"uptime_in_days": "41",
	"hz": "10",
	"lru_clock": "4566270",
	"config_file": "/etc/redis/redis.conf",

    // Clients
	"connected_clients": "19",
	"client_longest_output_list": "0",
	"client_biggest_input_buf": "0",
	"blocked_clients": "2",

    // Memory
	"used_memory": "1397544",
	"used_memory_human": "1.33M",
	"used_memory_rss": "4177920",
	"used_memory_peak": "2015928",
	"used_memory_peak_human": "1.92M",
	"used_memory_lua": "50176",
	"mem_fragmentation_ratio": "2.99",
	"mem_allocator": "jemalloc-3.6.0",

    // Persistence
	"loading": "0",
	"rdb_changes_since_last_save": "504968",
	"rdb_bgsave_in_progress": "0",
	"rdb_last_save_time": "1544502683",
	"rdb_last_bgsave_status": "ok",
	"rdb_last_bgsave_time_sec": "-1",
	"rdb_current_bgsave_time_sec": "-1",
	"aof_enabled": "0",
	"aof_rewrite_in_progress": "0",
	"aof_rewrite_scheduled": "0",
	"aof_last_rewrite_time_sec": "-1",
	"aof_current_rewrite_time_sec": "-1",
	"aof_last_bgrewrite_status": "ok",
	"aof_last_write_status": "ok",

    // Stats
	"total_connections_received": "242351",
	"total_commands_processed": "1547367",
	"instantaneous_ops_per_sec": "0",
	"total_net_input_bytes": "135497159",
	"total_net_output_bytes": "137918239",
	"instantaneous_input_kbps": "0.00",
	"instantaneous_output_kbps": "0.00",
	"rejected_connections": "0",
	"sync_full": "0",
	"sync_partial_ok": "0",
	"sync_partial_err": "0",
	"expired_keys": "115953",
	"evicted_keys": "0",
	"keyspace_hits": "141134",
	"keyspace_misses": "126717",
	"pubsub_channels": "2",
	"pubsub_patterns": "0",
	"latest_fork_usec": "0",
	"migrate_cached_sockets": "0",

    // Replication
	"role": "master",
	"connected_slaves": "0",
	"master_repl_offset": "0",
	"repl_backlog_active": "0",
	"repl_backlog_size": "1048576",
	"repl_backlog_first_byte_offset": "0",
	"repl_backlog_histlen": "0",

    // CPU
	"used_cpu_sys": "3075.78",
	"used_cpu_user": "2008.40",
	"used_cpu_sys_children": "0.00",
	"used_cpu_user_children": "0.00",

    // Cluster
	"cluster_enabled": "0",

    // Keyspace
	"db0": "keys=11,expires=0,avg_ttl=0",
	"db1": "keys=5811,expires=118,avg_ttl=75653011",
	"db2": "keys=135,expires=135,avg_ttl=57894404"
}