

class ParserState
{
}
ParserState.START = 0;
ParserState.BAG_NUBER_FOUND = 1;
ParserState.CHANGES_MAY_APPLY_DISCLAIMER_FOUND = 2;
ParserState.FEE_TOKEN_FOUND = 3;
ParserState.PERSONAL_ITEM_TOKEN_FOUND = 4;
ParserState.CARRYON_BAGGAGE_ALLOWANCE_TOKEN_FOUND = 5;
ParserState.CARRY_ON_PERSONAL_ITEMS_TOKEN_FOUND = 6;
ParserState.FIRST_SIZE_OR_WEIGHT_CONSTRAINTS_TOKEN_FOUND = 7;
ParserState.AND_TOKEN_FOUND = 8;
ParserState.SECOND_SIZE_OR_WEIGHT_CONSTRAINTS_TOKEN_FOUND = 9;
ParserState.BAGGAGE_CHARGES_DATA_NOT_AVAILABLE_TOKEN_FOUND = 10;
ParserState.NOT_PERMITTED_TOKEN_FOUND = 11;
ParserState.EXCESS_PIECE_TOKEN_FOUND = 12;
ParserState.EXTRA_HAND_BAGGAGE_TOKEN_FOUND = 13;
ParserState.UNCLASSIFIED_DESCRIPTION_FOUND = 14;

module.exports = ParserState;
