module.exports.migrations = [
	{
		name: 'GDSD-87-create_terminal_command_log_hist',
		perform: async db => db.query([
			"CREATE TABLE `terminal_command_log_hist` (",
			"  `id` bigint(20) NOT NULL,",
			"  `session_id` int(11) DEFAULT NULL,",
			"  `gds` varchar(10) DEFAULT NULL,",
			"  `type` varchar(50) DEFAULT NULL,",
			"  `is_mr` tinyint(1) DEFAULT NULL,",
			"  `dt` datetime NOT NULL,",
			"  `cmd` text,",
			"  `cmd_rq_id` bigint(20) DEFAULT NULL,",
			"  `output` blob NOT NULL,",
			"  `compression_type` tinyint(1) NOT NULL,",
			"  `dictionary` int(10) unsigned NOT NULL,",
			"  PRIMARY KEY (`id`)",
			"  KEY `session_id` (`session_id`)",
			"  KEY `type` (`type`)",
			") ENGINE=InnoDB DEFAULT CHARSET=utf8",
		].join('\n')),
	},
	{
		name: 'GDSD-87-create_terminal_command_log_hist_dictionary',
		perform: async db => db.query([
			"CREATE TABLE `terminal_command_log_hist_dictionary` (",
			"  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,",
			"  `gds` varchar(10) DEFAULT NULL,",
			"  `type` varchar(50) DEFAULT NULL,",
			"  `created` datetime NOT NULL,",
			"  `status` tinyint(1) NOT NULL DEFAULT '1',",
			"  `dictionary` blob NOT NULL,",
			"  PRIMARY KEY (`id`)",
			") ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8",
		].join('\n')),
	},
];