

class ParserState
{
}
ParserState.START = 'START';
ParserState.BA_BLOCK_START_LINE_FOUND = 'BA_BLOCK_START_LINE_FOUND';
ParserState.PASSENGER_TYPE_LINE_FOUND = 'PASSENGER_TYPE_LINE_FOUND';
ParserState.BA_BLOCK_SPECIFIC_SEGMENT_LINE_FOUND = 'BA_BLOCK_SPECIFIC_SEGMENT_LINE_FOUND';
ParserState.BAGGAGE_DISCOUNTS_DISCLAIMER_FOUND = 'BAGGAGE_DISCOUNTS_DISCLAIMER_FOUND';
ParserState.CARRYON_ALLOWANCE_BLOCK_START_LINE_FOUND = 'CARRYON_ALLOWANCE_BLOCK_START_LINE_FOUND';
ParserState.EMBARGO_BLOCK_START_LINE_FOUND = 'EMBARGO_BLOCK_START_LINE_FOUND';

module.exports = ParserState;
