
// namespace Gds\Parsers\Apollo;

const ApolloSvcParser = require('../../../../../../../backend/Transpiled/Gds/Parsers/Apollo/ApolloSvcParser/ApolloSvcParser.js');

const php = require('../../../../php.js');
class ApolloSvcParserTest extends require('../../../../Lib/TestCase.js')
{
    provideTestDumpList()  {
        let $list;

        $list = [];

        $list.push([
            php.implode(php.PHP_EOL, [
                ' 1 AA 3018  L SMFLAX  ERD  FOOD TO PURCHASE                1:30',
                '                      NON-SMOKING',
                '',
                '           OPERATED BY AMERICAN EAGLE',
                '           DEPARTS SMF TERMINAL B  - ARRIVES LAX TERMINAL 4',
                '           TSA SECURED FLIGHT',
                '',
                ' 2 AA  169  L LAXNRT  777  LUNCH\/DINNER                   11:40',
                '                      MOVIE\/TELEPHONE\/AUDIO PROGRAMMING\/',
                '                      DUTY FREE SALES\/NON-SMOKING\/',
                '                      IN-SEAT POWER SOURCE\/VIDEO\/LIBRARY',
                '',
                '           DEPARTS LAX TERMINAL 4  - ARRIVES NRT TERMINAL 2',
                '           TSA SECURED FLIGHT',
                '',
                ' 3 JL  745  L NRTMNL  767  MEAL                            4:40',
                '                      NON-SMOKING',
                '',
                '           DEPARTS NRT TERMINAL 2  - ARRIVES MNL TERMINAL 1',
                '',
                ' 4 JL  746  N MNLNRT  767  MEAL                            4:30',
                '                      NON-SMOKING',
                '',
                '           DEPARTS MNL TERMINAL 1  - ARRIVES NRT TERMINAL 2',
                '',
                ' 5 AA  170  N NRTLAX  777  DINNER\/BREAKFAST                9:55',
                '                      MOVIE\/TELEPHONE\/AUDIO PROGRAMMING\/',
                '                      DUTY FREE SALES\/NON-SMOKING\/',
                '                      IN-SEAT POWER SOURCE\/VIDEO\/LIBRARY',
                '',
                '           DEPARTS NRT TERMINAL 2  - ARRIVES LAX TERMINAL B',
                '           TSA SECURED FLIGHT',
                '',
                ' 6 AA 3075  N LAXSMF  ERD  FOOD TO PURCHASE                1:25',
                '                      NON-SMOKING',
                '',
                '           OPERATED BY AMERICAN EAGLE',
                '           DEPARTS LAX TERMINAL 4  - ARRIVES SMF TERMINAL B',
                '           TSA SECURED FLIGHT',
            ]),
            [
                {
                    'segmentNumber': 1,
                    'airline': 'AA',
                    'flightNumber': '3018',
                    'bookingClass': 'L',
                    'departureTerminal': 'B',
                    'arrivalTerminal': '4',
                    'operatedByText': 'OPERATED BY AMERICAN EAGLE',
                    'miscInfoText': 'TSA SECURED FLIGHT',
                    'legs': [
                        {
                            'departureAirport': 'SMF',
                            'destinationAirport': 'LAX',
                            'aircraft': 'ERD',
                            'mealOptions': 'FOOD TO PURCHASE',
                            'flightDuration': '1:30',
                            'inFlightServicesText': 'NON-SMOKING',
                        },
                    ],
                },
                {
                    'segmentNumber': 2,
                    'airline': 'AA',
                    'flightNumber': '169',
                    'bookingClass': 'L',
                    'departureTerminal': '4',
                    'arrivalTerminal': '2',
                    'operatedByText': '',
                    'miscInfoText': 'TSA SECURED FLIGHT',
                    'legs': [
                        {
                            'departureAirport': 'LAX',
                            'destinationAirport': 'NRT',
                            'aircraft': '777',
                            'mealOptions': 'LUNCH\/DINNER',
                            'flightDuration': '11:40',
                            'inFlightServicesText': php.implode(php.PHP_EOL, [
                                'MOVIE\/TELEPHONE\/AUDIO PROGRAMMING\/',
                                'DUTY FREE SALES\/NON-SMOKING\/',
                                'IN-SEAT POWER SOURCE\/VIDEO\/LIBRARY',
                            ]),
                        },
                    ],
                },
                {
                    'segmentNumber': 3,
                    'airline': 'JL',
                    'flightNumber': '745',
                    'bookingClass': 'L',
                    'departureTerminal': '2',
                    'arrivalTerminal': '1',
                    'operatedByText': '',
                    'miscInfoText': '',
                    'legs': [
                        {
                            'departureAirport': 'NRT',
                            'destinationAirport': 'MNL',
                            'aircraft': '767',
                            'mealOptions': 'MEAL',
                            'flightDuration': '4:40',
                            'inFlightServicesText': 'NON-SMOKING',
                        },
                    ],
                },
                {
                    'segmentNumber': 4,
                    'airline': 'JL',
                    'flightNumber': '746',
                    'bookingClass': 'N',
                    'departureTerminal': '1',
                    'arrivalTerminal': '2',
                    'operatedByText': '',
                    'miscInfoText': '',
                    'legs': [
                        {
                            'departureAirport': 'MNL',
                            'destinationAirport': 'NRT',
                            'aircraft': '767',
                            'mealOptions': 'MEAL',
                            'flightDuration': '4:30',
                            'inFlightServicesText': 'NON-SMOKING',
                        },
                    ],
                },
                {
                    'segmentNumber': 5,
                    'airline': 'AA',
                    'flightNumber': '170',
                    'bookingClass': 'N',
                    'departureTerminal': '2',
                    'arrivalTerminal': 'B',
                    'operatedByText': '',
                    'miscInfoText': 'TSA SECURED FLIGHT',
                    'legs': [
                        {
                            'departureAirport': 'NRT',
                            'destinationAirport': 'LAX',
                            'aircraft': '777',
                            'mealOptions': 'DINNER\/BREAKFAST',
                            'flightDuration': '9:55',
                            'inFlightServicesText': php.implode(php.PHP_EOL, [
                                'MOVIE\/TELEPHONE\/AUDIO PROGRAMMING\/',
                                'DUTY FREE SALES\/NON-SMOKING\/',
                                'IN-SEAT POWER SOURCE\/VIDEO\/LIBRARY',
                            ]),
                        },
                    ],
                },
                {
                    'segmentNumber': 6,
                    'airline': 'AA',
                    'flightNumber': '3075',
                    'bookingClass': 'N',
                    'departureTerminal': '4',
                    'arrivalTerminal': 'B',
                    'operatedByText': 'OPERATED BY AMERICAN EAGLE',
                    'miscInfoText': 'TSA SECURED FLIGHT',
                    'legs': [
                        {
                            'departureAirport': 'LAX',
                            'destinationAirport': 'SMF',
                            'aircraft': 'ERD',
                            'mealOptions': 'FOOD TO PURCHASE',
                            'flightDuration': '1:25',
                            'inFlightServicesText': 'NON-SMOKING',
                        },
                    ],
                },
            ],
        ]);

        $list.push([
            php.implode(php.PHP_EOL, [
                ' 1 DL 2464  V TPAJFK  717  REFRESH AT COST                 2:44',
                '                      ENTERTAINMENT ON DEMAND\/                 ',
                '                      IN-SEAT POWER SOURCE\/WI-FI\/NON-SMOKING\/  ',
                '                      AMENITIES SUBJECT TO CHANGE              ',
                '                                                               ',
                '                                     ARRIVES JFK TERMINAL 4    ',
                '           TSA SECURED FLIGHT                                  ',
                '                                                               ',
                ' 2 DL  473  V JFKNRT  777  DINNER                         14:15',
                '                      MOVIE\/ENTERTAINMENT ON DEMAND\/           ',
                '                      IN-SEAT POWER SOURCE\/VIDEO\/LIBRARY\/WI-FI\/',
                '                      LIE-FLAT SEAT BUSINESS\/NON-SMOKING\/      ',
                '                      AMENITIES SUBJECT TO CHANGE              ',
                '                                                               ',
                '              NRTMNL  744  DINNER                          5:05',
                '                      MOVIE\/ENTERTAINMENT ON DEMAND\/           ',
                '                      IN-SEAT POWER SOURCE\/VIDEO\/LIBRARY\/WI-FI\/',
                '                      LIE-FLAT SEAT BUSINESS\/NON-SMOKING\/      ',
                '                      AMENITIES SUBJECT TO CHANGE              ',
                '                                                               ',
                '           DEPARTS JFK TERMINAL 4  - ARRIVES MNL TERMINAL 3    ',
                '           PLANE CHANGE AT NRT                                 ',
                '           TSA SECURED FLIGHT                                  ',
                '                                                               ',
                ' 3 DL  172  V MNLNRT  744  LUNCH                           4:05',
                '                      MOVIE\/ENTERTAINMENT ON DEMAND\/           ',
                '                      IN-SEAT POWER SOURCE\/VIDEO\/LIBRARY\/WI-FI\/',
                '                      LIE-FLAT SEAT BUSINESS\/NON-SMOKING\/      ',
                '                      AMENITIES SUBJECT TO CHANGE              ',
                '                                                               ',
                '              NRTJFK  777  DINNER                         13:04',
                '                      MOVIE\/ENTERTAINMENT ON DEMAND\/           ',
                '                      IN-SEAT POWER SOURCE\/VIDEO\/LIBRARY\/WI-FI\/',
                '                      LIE-FLAT SEAT BUSINESS\/NON-SMOKING\/      ',
                '                      AMENITIES SUBJECT TO CHANGE              ',
                '                                                               ',
                '           DEPARTS MNL TERMINAL 3  - ARRIVES JFK TERMINAL 4    ',
                '           PLANE CHANGE AT NRT                                 ',
                '           TSA SECURED FLIGHT                                  ',
                '                                                               ',
                ' 5 DL  411  X JFKTPA  M88  REFRESH AT COST                 3:15',
                '                      ENTERTAINMENT ON DEMAND\/WI-FI\/           ',
                '                      NON-SMOKING\/AMENITIES SUBJECT TO CHANGE  ',
                '                                                               ',
                '           DEPARTS JFK TERMINAL 4                              ',
                '           TSA SECURED FLIGHT                                  ',
            ]),
            [
                {
                    'segmentNumber': 1,
                    'airline': 'DL',
                    'flightNumber': '2464',
                    'bookingClass': 'V',
                    'departureTerminal': '',
                    'arrivalTerminal': '4',
                    'operatedByText': '',
                    'miscInfoText': 'TSA SECURED FLIGHT',
                    'legs': [
                        {
                            'departureAirport': 'TPA',
                            'destinationAirport': 'JFK',
                            'aircraft': '717',
                            'mealOptions': 'REFRESH AT COST',
                            'flightDuration': '2:44',
                            'inFlightServicesText': php.implode(php.PHP_EOL, [
                                'ENTERTAINMENT ON DEMAND\/',
                                'IN-SEAT POWER SOURCE\/WI-FI\/NON-SMOKING\/',
                                'AMENITIES SUBJECT TO CHANGE',
                            ]),
                        },
                    ],
                },
                {
                    'segmentNumber': 2,
                    'airline': 'DL',
                    'flightNumber': '473',
                    'bookingClass': 'V',
                    'departureTerminal': '4',
                    'arrivalTerminal': '3',
                    'operatedByText': '',
                    'miscInfoText': php.implode(php.PHP_EOL, ['PLANE CHANGE AT NRT','TSA SECURED FLIGHT']),
                    'legs': [
                        {
                            'departureAirport': 'JFK',
                            'destinationAirport': 'NRT',
                            'aircraft': '777',
                            'mealOptions': 'DINNER',
                            'flightDuration': '14:15',
                            'inFlightServicesText': php.implode(php.PHP_EOL, [
                                'MOVIE\/ENTERTAINMENT ON DEMAND\/',
                                'IN-SEAT POWER SOURCE\/VIDEO\/LIBRARY\/WI-FI\/',
                                'LIE-FLAT SEAT BUSINESS\/NON-SMOKING\/',
                                'AMENITIES SUBJECT TO CHANGE',
                            ]),
                        },
                        {
                            'departureAirport': 'NRT',
                            'destinationAirport': 'MNL',
                            'aircraft': '744',
                            'mealOptions': 'DINNER',
                            'flightDuration': '5:05',
                            'inFlightServicesText': php.implode(php.PHP_EOL, [
                                'MOVIE\/ENTERTAINMENT ON DEMAND\/',
                                'IN-SEAT POWER SOURCE\/VIDEO\/LIBRARY\/WI-FI\/',
                                'LIE-FLAT SEAT BUSINESS\/NON-SMOKING\/',
                                'AMENITIES SUBJECT TO CHANGE',
                            ]),
                        },
                    ],
                },
                {
                    'segmentNumber': 3,
                    'airline': 'DL',
                    'flightNumber': '172',
                    'bookingClass': 'V',
                    'departureTerminal': '3',
                    'arrivalTerminal': '4',
                    'operatedByText': '',
                    'miscInfoText': php.implode(php.PHP_EOL, ['PLANE CHANGE AT NRT','TSA SECURED FLIGHT']),
                    'legs': [
                        {
                            'departureAirport': 'MNL',
                            'destinationAirport': 'NRT',
                            'aircraft': '744',
                            'mealOptions': 'LUNCH',
                            'flightDuration': '4:05',
                            'inFlightServicesText': php.implode(php.PHP_EOL, [
                                'MOVIE\/ENTERTAINMENT ON DEMAND\/',
                                'IN-SEAT POWER SOURCE\/VIDEO\/LIBRARY\/WI-FI\/',
                                'LIE-FLAT SEAT BUSINESS\/NON-SMOKING\/',
                                'AMENITIES SUBJECT TO CHANGE',
                            ]),
                        },
                        {
                            'departureAirport': 'NRT',
                            'destinationAirport': 'JFK',
                            'aircraft': '777',
                            'mealOptions': 'DINNER',
                            'flightDuration': '13:04',
                            'inFlightServicesText': php.implode(php.PHP_EOL, [
                                'MOVIE\/ENTERTAINMENT ON DEMAND\/',
                                'IN-SEAT POWER SOURCE\/VIDEO\/LIBRARY\/WI-FI\/',
                                'LIE-FLAT SEAT BUSINESS\/NON-SMOKING\/',
                                'AMENITIES SUBJECT TO CHANGE',
                            ]),
                        },
                    ],
                },
                {
                    'segmentNumber': 5,
                    'airline': 'DL',
                    'flightNumber': '411',
                    'bookingClass': 'X',
                    'departureTerminal': '4',
                    'arrivalTerminal': '',
                    'operatedByText': '',
                    'miscInfoText': 'TSA SECURED FLIGHT',
                    'legs': [
                        {
                            'departureAirport': 'JFK',
                            'destinationAirport': 'TPA',
                            'aircraft': 'M88',
                            'mealOptions': 'REFRESH AT COST',
                            'flightDuration': '3:15',
                            'inFlightServicesText': php.implode(php.PHP_EOL, ['ENTERTAINMENT ON DEMAND\/WI-FI\/','NON-SMOKING\/AMENITIES SUBJECT TO CHANGE']),
                        },
                    ],
                },
            ],
        ]);

        // >*V9M9RY; with 4 hidden stops. No aircraft. Duration without hours.
        // these hidden stops are train stations, not airports
        $list.push([
            php.implode(php.PHP_EOL, [
                ' 1 9B 9219  M BRUZGP  TRN                                   :13',
                '                      NON-SMOKING                              ',
                '                                                               ',
                '              ZGPZWE  TRN                                   :19',
                '                      NON-SMOKING                              ',
                '                                                               ',
                '              ZWEQRH  TRN                                  1:11',
                '                      NON-SMOKING                              ',
                '                                                               ',
                '              QRHZYH  TRN                                   :20',
                '                      NON-SMOKING                              ',
                '                                                               ',
                '              ZYHAMS  TRN                                   :30',
                '                      NON-SMOKING                              ',
                '                                                               ',
                '           OPERATED BY SNCB EUROPE\/NS INTERNATIONAL            ',
                '                                                               ',
            ]),
            [
                {
                    'segmentNumber': 1,
                    'airline': '9B',
                    'flightNumber': '9219',
                    'bookingClass': 'M',
                    'legs': [
                        {'departureAirport': 'BRU','destinationAirport': 'ZGP','flightDuration': '0:13'},
                        {'departureAirport': 'ZGP','destinationAirport': 'ZWE','flightDuration': '0:19'},
                        {'departureAirport': 'ZWE','destinationAirport': 'QRH','flightDuration': '1:11'},
                        {'departureAirport': 'QRH','destinationAirport': 'ZYH','flightDuration': '0:20'},
                        {'departureAirport': 'ZYH','destinationAirport': 'AMS','flightDuration': '0:30'},
                    ],
                },
            ],
        ]);

        // with plane change - M80/788
        $list.push([
            php.implode(php.PHP_EOL, [
                ' 1 QR 5297  Y MSPORD  M80                                  1:41',
                '                      NON-SMOKING\/WI-FI                        ',
                '                                                               ',
                '              ORDLHR  788                                  7:35',
                '                      NON-SMOKING\/MOVIE\/AUDIO PROGRAMMING\/     ',
                '                      VIDEO\/LIBRARY\/WI-FI                      ',
                '                                                               ',
                '           OPERATED BY AMERICAN AIRLINES                       ',
                '           DEPARTS MSP TERMINAL 1  - ARRIVES LHR TERMINAL 3    ',
                '           PLANE CHANGE AT ORD                                 ',
                '           VALID FOR INTL ONLINE CONNECTIONS ONLY              ',
                '           TSA SECURED FLIGHT                                  ',
                '                                                               ',
                ' 2 QR    4  Y LHRDOH  388  MEAL                            6:44',
                '                      NON-SMOKING                              ',
                '                                                               ',
                '           DEPARTS LHR TERMINAL 4                              ',
                '                                                               ',
                ' 3 QR  970  Y DOHSGN  333  MEAL                            7:05',
                '                      NON-SMOKING                              ',
                '                                                               ',
                '              SGNPNH  332  MEAL                             :50',
                '                      NON-SMOKING                              ',
                '                                                               ',
                '           PLANE CHANGE AT SGN                                 ',
                '                                                               ',
                ' 4 QR  971  L PNHSGN  332  MEAL                            1:05',
                '                      NON-SMOKING                              ',
                '                                                               ',
                '              SGNDOH  332  MEAL                            8:40',
                '                      NON-SMOKING                              ',
                '                                                               ',
                '                                                               ',
                ' 5 QR  725  L DOHORD  77W  MEAL                           14:45',
                '                      NON-SMOKING                              ',
                '                                                               ',
                '                                     ARRIVES ORD TERMINAL 5    ',
                '           TSA SECURED FLIGHT                                  ',
                '                                                               ',
                ' 6 QR 5365  L ORDMSP  738                                  1:29',
                '                      NON-SMOKING\/AUDIO PROGRAMMING\/           ',
                '                      VIDEO\/LIBRARY\/WI-FI                      ',
                '                                                               ',
                '           OPERATED BY AMERICAN AIRLINES                       ',
                '           DEPARTS ORD TERMINAL 3  - ARRIVES MSP TERMINAL 1    ',
                '           VALID FOR ONLINE CONNECTIONS ONLY                   ',
                '           TSA SECURED FLIGHT                                  ',
                '                                                               ',
                'CO2 CALCULATED PER PERSON BY CLIMATENEUTRALGROUP.COM\/OFFSET-NOW',
                '    CO2 MSPORD ECONOMY      94.95 KG PREMIUM      94.95 KG     ',
                '    CO2 ORDLHR ECONOMY     589.72 KG PREMIUM    1297.39 KG     ',
                '    CO2 LHRDOH ECONOMY     486.86 KG PREMIUM    1071.10 KG     ',
                '    CO2 DOHSGN ECONOMY     557.65 KG PREMIUM    1226.83 KG     ',
                '    CO2 SGNPNH ECONOMY      37.78 KG PREMIUM      37.78 KG     ',
                '    CO2 PNHSGN ECONOMY      37.78 KG PREMIUM      37.78 KG     ',
                '    CO2 SGNDOH ECONOMY     557.65 KG PREMIUM    1226.83 KG     ',
                '    CO2 DOHORD ECONOMY    1064.91 KG PREMIUM    2342.81 KG     ',
                '    CO2 ORDMSP ECONOMY      94.95 KG PREMIUM      94.95 KG     ',
                '    CO2 TOTAL  ECONOMY    3522.27 KG PREMIUM    7430.43 KG     ',
            ]),
            [
                {
                    'segmentNumber': 1,
                    'airline': 'QR',
                    'flightNumber': '5297',
                    'bookingClass': 'Y',
                    'legs': [
                        {'aircraft': 'M80','departureAirport': 'MSP','destinationAirport': 'ORD'},
                        {'aircraft': '788','departureAirport': 'ORD','destinationAirport': 'LHR'},
                    ],
                },
                {'segmentNumber': 2},
                {'segmentNumber': 3},
                {'segmentNumber': 4},
                {'segmentNumber': 5},
                {'segmentNumber': 6},
            ],
        ]);

        return $list;
    }

    /**
     * @test
     * @dataProvider provideTestDumpList
     */
    testParser($dump, $expectedResult)  {
        let $actualResult;

        $actualResult = ApolloSvcParser.parse($dump);
        this.assertArrayElementsSubset($expectedResult, $actualResult);
    }

	getTestMapping() {
		return [
			[this.provideTestDumpList, this.testParser],
		];
	}
}
module.exports = ApolloSvcParserTest;
