const stubPccs = require('../../../../../../../data/stubPccs.js');
const SqlUtil = require('klesun-node-tools/src/Utils/SqlUtil.js');
const Pccs = require('../../../../../../../../backend/Repositories/Pccs.js');
const RunCmdRq = require('../../../../../../../../backend/Transpiled/Rbs/GdsDirect/Actions/Apollo/RunCmdRq.js');
const GdsDirectDefaults = require('../../../../../../../../backend/Utils/Testing/GdsDirectDefaults.js');
const Rej = require('klesun-node-tools/src/Rej.js');
const {coverExc} = require('klesun-node-tools/src/Lang.js');
const {nonEmpty} = require('klesun-node-tools/src/Lang.js');
const _ = require('lodash');

class RunCmdRqHbFexTest extends require('klesun-node-tools/src/Transpiled/Lib/TestCase.js') {
	provideTestCases() {
		const list = [];

		list.push({
			'title': 'HB:FEX action example',
			'input': {
				'cmdRequested': 'HB:FEX',
			},
			'output': {
				'status': 'executed',
				'calledCommands': [
					{
						'cmd': 'HB:FEX',
						'output': 'SEE MASK FORM BELOW',
					},
				],
				'actions': [
					{
						'type': 'displayExchangeMask',
						'data': {
							//">$EX NAME UZUMAKI/NARUTO                     PSGR  1/ 1",
							//"FARE USD   901.40  TOTAL USD   983.30",
							//"TX1 USD   67.60 US   TX2 USD   14.30 XT   TX3               "
							'headerData': {
								lastName: 'UZUMAKI',
								firstName: 'NARUTO',
								majorNumber: '1',
								minorNumber: '1',
								baseFareCurrency: 'USD',
								baseFareAmount: '901.40',
								netPriceCurrency: 'USD',
								netPriceAmount: '983.30',
								equivalentPart: '',
								taxCurrency1: 'USD',
								taxAmount1: '67.60',
								taxCode1: 'US',
								taxCurrency2: 'USD',
								taxAmount2: '14.30',
								taxCode2: 'XT',
								taxCurrency3: undefined,
								taxAmount3: undefined,
								taxCode3: undefined,
								exchangedTicketCurrency: 'USD',
							},
							'fields': [
								{'enabled': true, 'key': 'exchangedTicketNumber', 'value': ''},
								{'enabled': true, 'key': 'exchangedTicketExtension', 'value': ''},
								{'enabled': true, 'key': 'ticketNumber1', 'value': ''},
								{'enabled': true, 'key': 'couponNumber1', 'value': ''},
								{'enabled': true, 'key': 'ticketNumber2', 'value': ''},
								{'enabled': true, 'key': 'couponNumber2', 'value': ''},
								{'enabled': true, 'key': 'commission', 'value': ''},
								{'enabled': true, 'key': 'originalFormOfPayment', 'value': ''},
								{'enabled': true, 'key': 'evenIndicator', 'value': ''},
								{'enabled': true, 'key': 'exchangedTicketTotalValue', 'value': ''},
								{'enabled': false, 'key': 'originalBoardPoint', 'value': ''},
								{'enabled': false, 'key': 'originalOffPoint', 'value': ''},
								{'enabled': true, 'key': 'taxAmount1', 'value': ''},
								{'enabled': true, 'key': 'taxCode1', 'value': ''},
								{'enabled': true, 'key': 'taxAmount2', 'value': ''},
								{'enabled': true, 'key': 'taxCode2', 'value': ''},
								{'enabled': true, 'key': 'taxAmount3', 'value': ''},
								{'enabled': true, 'key': 'taxCode3', 'value': ''},
								{'enabled': true, 'key': 'originalIssuePoint', 'value': ''},
								{'enabled': true, 'key': 'originalIssueDate', 'value': ''},
								{'enabled': false, 'key': 'originalAgencyIata', 'value': ''},
								{'enabled': true, 'key': 'originalTicketStar', 'value': ''},
								{'enabled': false, 'key': 'originalTicketStarExtension', 'value': ''},
								{'enabled': false, 'key': 'originalInvoiceNumber', 'value': ''},
								{'enabled': true, 'key': 'penaltyAmount', 'value': ''},
								{'enabled': true, 'key': 'commOnPenaltyAmount', 'value': ''},
							],
							'maskOutput': [
								'>$EX NAME UZUMAKI/NARUTO                     PSGR  1/ 1',
								'FARE USD   901.40  TOTAL USD   983.30',
								'TX1 USD   67.60 US   TX2 USD   14.30 XT   TX3               ',
								'',
								'EXCHANGE TKTS ;..............-;...  CPN ALL',
								'TKT1;.............. CPN;.... TKT2;.............. CPN;....',
								'COMM;.........  ORIG FOP;................... EVEN;.',
								'',
								'TTL VALUE OF EX TKTS USD;.............  ORIG BRD/OFF;...;...',
								'TX1 USD;.......;..   TX2 USD;.......;..   TX3 USD;.......;..',
								'ORIG ISS;...... ORIG DATE;....... ORIG IATA NBR;.........',
								'ORIG TKT;..............-;...  ORIG INV NBR;.........',
								'PENALTY USD;............  COMM ON PENALTY;...........',
								'><',
							].join('\n'),
						},
					},
				],
			},
			'sessionInfo': {
				'initialState': _.extend(GdsDirectDefaults.makeDefaultApolloState(), {
					'agent_id': 8050,
					'hasPnr': true,
					'isPnrStored': true,
					'pcc': '2F3K',
					'recordLocator': 'PZWSV5',
				}),
				'initialCommands': [],
				'performedCommands': [
					{
						'cmd': '*R',
						'output': [
							'CREATED IN GDS DIRECT BY AKLESUNS',
							'PZWSV5/WS QSBYC DPBVWS  AG 05578602 01APR',
							' 1.1UZUMAKI/NARUTO ',
							' 1 UA 613Y 25JUN SFOLAX HK1   630A  816A *         TU   E',
							' 2 TUR ZZ BK1  YYZ 15FEB-RETENTION LINE',
							' 3 TUR ZZ BK1  YYZ 15FEB-RETENTION LINE',
							'FONE-SFOAS/800-750-2238 ASAP CUSTOMER SUPPORT',
							'FOP:-VIXXXXXXXXXXXX1111/D1221/*ABC123',
							'TKTG-TAU/01APR',
							'*** LINEAR FARE DATA EXISTS *** >*LF; ',
							'ATFQ-TKTE/$B-*2F3K/FEX/ET/TA2F3K/CUA',
							' FQ-USD 901.40/USD 67.60US/USD 14.30XT/USD 983.30 - 1APR YAA0AFEY',
							')><',
						].join('\n'),
					},
					{
						'cmd': 'MR',
						'output': [
							'GFAX-SSRDOCSUAHK1/////10MAY90/M//UZUMMAKI/NARUTO-1UZUMAKI/NARUTO',
							'   2 SSRADTK1VKK1.TKT UA SEGS BY 22JUN19 TO AVOID AUTO CXL /EARLIER',
							'   3 SSRADTK1VKK1.TICKETING MAY BE REQUIRED BY FARE RULE',
							'RMKS-GD-AKLESUNS/6206/LEAD-8013096 IN 2F3K',
							'ACKN-UA JSMMZL   01APR 1029                       ',
							'><',
						].join('\n'),
					},
					{
						'cmd': 'HB:FEX',
						'output': [
							'>$EX NAME UZUMAKI/NARUTO                     PSGR  1/ 1',
							'FARE USD   901.40  TOTAL USD   983.30',
							'TX1 USD   67.60 US   TX2 USD   14.30 XT   TX3               ',
							'',
							'EXCHANGE TKTS ;..............-;...  CPN ALL',
							'TKT1;.............. CPN;.... TKT2;.............. CPN;....',
							'COMM;.........  ORIG FOP;................... EVEN;.',
							'',
							'TTL VALUE OF EX TKTS USD;.............  ORIG BRD/OFF;...;...',
							'TX1 USD;.......;..   TX2 USD;.......;..   TX3 USD;.......;..',
							'ORIG ISS;...... ORIG DATE;....... ORIG IATA NBR;.........',
							'ORIG TKT;..............-;...  ORIG INV NBR;.........',
							'PENALTY USD;............  COMM ON PENALTY;...........',
							'><',
						].join('\n'),
					},
					{
						cmd: '*HA',
						output: [
							'INVLD',
							'><',
						].join('\n'),
					},
				],
			},
		});

		list.push({
			'title': 'HB:FEX action example with ticket number (artificial, exchange of normal ticket)',
			'input': {
				'cmdRequested': 'HB:FEX016 7293 600184',
			},
			'output': {
				'status': 'executed',
				'calledCommands': [
					{
						'cmd': 'HB:FEX016 7293 600184',
						'output': 'SEE MASK FORM BELOW',
					},
				],
				'actions': [
					{
						'type': 'displayExchangeMask',
						'data': {
							'mcoRows': [],
							//">$EX NAME RICO/SRICO                         PSGR  1/ 1",
							//"FARE USD   901.40  TOTAL USD   983.30",
							//"TX1 USD   67.60 US   TX2 USD   14.30 XT   TX3               ",
							'headerData': {
								lastName: 'RICO',
								firstName: 'SRICO',
								majorNumber: '1',
								minorNumber: '1',
								baseFareCurrency: 'USD',
								baseFareAmount: '901.40',
								netPriceCurrency: 'USD',
								netPriceAmount: '983.30',
								equivalentPart: '',
								taxCurrency1: 'USD',
								taxAmount1: '67.60',
								taxCode1: 'US',
								taxCurrency2: 'USD',
								taxAmount2: '14.30',
								taxCode2: 'XT',
								taxCurrency3: undefined,
								taxAmount3: undefined,
								taxCode3: undefined,
								exchangedTicketCurrency: 'USD',
							},
							'fields': [
								{'enabled': true, 'key': 'exchangedTicketNumber', 'value': ''},
								{'enabled': true, 'key': 'exchangedTicketExtension', 'value': ''},
								{'enabled': false, 'key': 'ticketNumber1', 'value': '01672936001844'},
								{'enabled': false, 'key': 'couponNumber1', 'value': '1'},
								{'enabled': true, 'key': 'ticketNumber2', 'value': ''},
								{'enabled': true, 'key': 'couponNumber2', 'value': ''},
								{'enabled': true, 'key': 'commission', 'value': ''},
								{'enabled': true, 'key': 'originalFormOfPayment', 'value': ''},
								{'enabled': true, 'key': 'evenIndicator', 'value': ''},
								{'enabled': false, 'key': 'exchangedTicketTotalValue', 'value': '983.30'},
								{'enabled': false, 'key': 'originalBoardPoint', 'value': 'SFO'},
								{'enabled': false, 'key': 'originalOffPoint', 'value': 'LAX'},
								{'enabled': false, 'key': 'taxAmount1', 'value': '67.60'},
								{'enabled': false, 'key': 'taxCode1', 'value': 'US'},
								{'enabled': false, 'key': 'taxAmount2', 'value': '14.30'},
								{'enabled': false, 'key': 'taxCode2', 'value': 'XT'},
								{'enabled': true, 'key': 'taxAmount3', 'value': ''},
								{'enabled': true, 'key': 'taxCode3', 'value': ''},
								{'enabled': false, 'key': 'originalIssuePoint', 'value': 'SFO'},
								{'enabled': false, 'key': 'originalIssueDate', 'value': '25MAR19'},
								{'enabled': false, 'key': 'originalAgencyIata', 'value': '05578602'},
								{'enabled': false, 'key': 'originalTicketStar', 'value': '*'},
								{'enabled': false, 'key': 'originalTicketStarExtension', 'value': ''},
								{'enabled': false, 'key': 'originalInvoiceNumber', 'value': ''},
								{'enabled': true, 'key': 'penaltyAmount', 'value': ''},
								{'enabled': true, 'key': 'commOnPenaltyAmount', 'value': ''},
							],
							'maskOutput': [
								'>$EX NAME RICO/SRICO                         PSGR  1/ 1',
								'FARE USD   901.40  TOTAL USD   983.30',
								'TX1 USD   67.60 US   TX2 USD   14.30 XT   TX3               ',
								'',
								'EXCHANGE TKTS ;..............-;...  CPN ALL',
								'TKT1;01672936001844 CPN;1... TKT2;.............. CPN;....',
								'COMM;.........  ORIG FOP;................... EVEN;.',
								'',
								'TTL VALUE OF EX TKTS USD;983.30.......  ORIG BRD/OFF;SFO;LAX',
								'TX1 USD;67.60..;US   TX2 USD;14.30..;XT   TX3 USD;.......;..',
								'ORIG ISS;SFO... ORIG DATE;25MAR19 ORIG IATA NBR;05578602.',
								'ORIG TKT;*.............-;...  ORIG INV NBR;.........',
								'PENALTY USD;............  COMM ON PENALTY;...........',
								'><',
							].join('\n'),
						},
					},
				],
			},
			'sessionInfo': {
				'initialState': _.extend(GdsDirectDefaults.makeDefaultApolloState(), {
					'agent_id': 8050,
					'hasPnr': true,
					'isPnrStored': true,
					'pcc': '2F3K',
					'recordLocator': 'PZWSV5',
				}),
				'initialCommands': [],
				'performedCommands': [
					{
						'cmd': '*R',
						'output': [
							'CREATED IN GDS DIRECT BY AKLESUNS',
							'PZWSV5/WS QSBYC DPBVWS  AG 05578602 01APR',
							' 1.1UZUMAKI/NARUTO ',
							' 1 UA 613Y 25JUN SFOLAX HK1   630A  816A *         TU   E',
							' 2 TUR ZZ BK1  YYZ 15FEB-RETENTION LINE',
							' 3 TUR ZZ BK1  YYZ 15FEB-RETENTION LINE',
							'FONE-SFOAS/800-750-2238 ASAP CUSTOMER SUPPORT',
							'FOP:-VIXXXXXXXXXXXX1111/D1221/*ABC123',
							'TKTG-TAU/01APR',
							'*** LINEAR FARE DATA EXISTS *** >*LF; ',
							'ATFQ-TKTE/$B-*2F3K/FEX/ET/TA2F3K/CUA',
							' FQ-USD 901.40/USD 67.60US/USD 14.30XT/USD 983.30 - 1APR YAA0AFEY',
							')><',
						].join('\n'),
					},
					{
						'cmd': 'MR',
						'output': [
							'GFAX-SSRDOCSUAHK1/////10MAY90/M//UZUMMAKI/NARUTO-1UZUMAKI/NARUTO',
							'   2 SSRADTK1VKK1.TKT UA SEGS BY 22JUN19 TO AVOID AUTO CXL /EARLIER',
							'   3 SSRADTK1VKK1.TICKETING MAY BE REQUIRED BY FARE RULE',
							'RMKS-GD-AKLESUNS/6206/LEAD-8013096 IN 2F3K',
							'ACKN-UA JSMMZL   01APR 1029                       ',
							'><',
						].join('\n'),
					},
					{
						'cmd': 'HB:FEX016 7293 600184',
						'output': [
							'>$EX NAME RICO/SRICO                         PSGR  1/ 1',
							'FARE USD   901.40  TOTAL USD   983.30',
							'TX1 USD   67.60 US   TX2 USD   14.30 XT   TX3               ',
							'',
							'EXCHANGE TKTS ;..............-;...  CPN ALL',
							'TKT1;01672936001844 CPN;1... TKT2;.............. CPN;....',
							'COMM;.........  ORIG FOP;................... EVEN;.',
							'',
							'TTL VALUE OF EX TKTS USD;983.30.......  ORIG BRD/OFF;SFO;LAX',
							'TX1 USD;67.60..;US   TX2 USD;14.30..;XT   TX3 USD;.......;..',
							'ORIG ISS;SFO... ORIG DATE;25MAR19 ORIG IATA NBR;05578602.',
							'ORIG TKT;*.............-;...  ORIG INV NBR;.........',
							'PENALTY USD;............  COMM ON PENALTY;...........',
							'><',
						].join('\n'),
					},
					{
						cmd: '*HA',
						output: [
							'INVLD',
							'><',
						].join('\n'),
					},
				],
			},
		});

		list.push({
			'title': 'HB:FEX with ticket number (real, exchange of exchange)',
			'input': {
				'cmdRequested': 'HB:FEX016 7289 106161',
			},
			'output': {
				'status': 'executed',
				'calledCommands': [
					{
						'cmd': 'HB:FEX016 7289 106161',
						'output': 'SEE MASK FORM BELOW',
					},
				],
				'actions': [
					{
						'type': 'displayExchangeMask',
						'data': {
							'mcoRows': [],
							//">$EX NAME UZUMAKI/NARUTO                     PSGR  1/ 1",
							//"FARE USD   901.40  TOTAL USD   983.30",
							//"TX1 USD   67.60 US   TX2 USD   14.30 XT   TX3               ",
							'headerData': {
								lastName: 'UZUMAKI',
								firstName: 'NARUTO',
								majorNumber: '1',
								minorNumber: '1',
								baseFareCurrency: 'USD',
								baseFareAmount: '901.40',
								netPriceCurrency: 'USD',
								netPriceAmount: '983.30',
								equivalentPart: '',
								taxCurrency1: 'USD',
								taxAmount1: '67.60',
								taxCode1: 'US',
								taxCurrency2: 'USD',
								taxAmount2: '14.30',
								taxCode2: 'XT',
								taxCurrency3: undefined,
								taxAmount3: undefined,
								taxCode3: undefined,
								exchangedTicketCurrency: 'USD',
							},
							'fields': [
								{'enabled': true, 'key': 'exchangedTicketNumber', 'value': ''},
								{'enabled': true, 'key': 'exchangedTicketExtension', 'value': ''},
								{'enabled': false, 'key': 'ticketNumber1', 'value': '01672891061612'},
								{'enabled': false, 'key': 'couponNumber1', 'value': '1'},
								{'enabled': true, 'key': 'ticketNumber2', 'value': ''},
								{'enabled': true, 'key': 'couponNumber2', 'value': ''},
								{'enabled': true, 'key': 'commission', 'value': ''},
								{'enabled': false, 'key': 'originalFormOfPayment', 'value': 'CK'},
								{'enabled': true, 'key': 'evenIndicator', 'value': ''},
								{'enabled': false, 'key': 'exchangedTicketTotalValue', 'value': '983.30'},
								{'enabled': false, 'key': 'originalBoardPoint', 'value': 'SFO'},
								{'enabled': false, 'key': 'originalOffPoint', 'value': 'LAX'},
								{'enabled': false, 'key': 'taxAmount1', 'value': '67.60'},
								{'enabled': false, 'key': 'taxCode1', 'value': 'US'},
								{'enabled': false, 'key': 'taxAmount2', 'value': '14.30'},
								{'enabled': false, 'key': 'taxCode2', 'value': 'XT'},
								{'enabled': true, 'key': 'taxAmount3', 'value': ''},
								{'enabled': true, 'key': 'taxCode3', 'value': ''},
								{'enabled': false, 'key': 'originalIssuePoint', 'value': 'SFO'},
								{'enabled': false, 'key': 'originalIssueDate', 'value': '02APR19'},
								{'enabled': false, 'key': 'originalAgencyIata', 'value': '00000000 '},
								{'enabled': false, 'key': 'originalTicketStar', 'value': '0161111111111'},
								{'enabled': false, 'key': 'originalTicketStarExtension', 'value': ''},
								{'enabled': false, 'key': 'originalInvoiceNumber', 'value': ''},
								{'enabled': true, 'key': 'penaltyAmount', 'value': ''},
								{'enabled': true, 'key': 'commOnPenaltyAmount', 'value': ''},
							],
							'maskOutput': [
								'>$EX NAME UZUMAKI/NARUTO                     PSGR  1/ 1',
								'FARE USD   901.40  TOTAL USD   983.30',
								'TX1 USD   67.60 US   TX2 USD   14.30 XT   TX3               ',
								'',
								'EXCHANGE TKTS ;..............-;...  CPN ALL',
								'TKT1;01672891061612 CPN;1... TKT2;.............. CPN;....',
								'COMM;.........  ORIG FOP;CK................. EVEN;.',
								'',
								'TTL VALUE OF EX TKTS USD;983.30.........ORIG BRD/OFF;SFO;LAX',
								'TX1 USD;67.60..;US   TX2 USD;14.30..;XT   TX3 USD;.......;..',
								'ORIG ISS;SFO....ORIG DATE;02APR19 ORIG IATA NBR;00000000 ',
								'ORIG TKT;0161111111111.-;...  ORIG INV NBR;.........',
								'PENALTY USD;............  COMM ON PENALTY;...........',
								'><',
							].join('\n'),
						},
					},
				],
			},
			'sessionInfo': {
				'initialState': _.extend(GdsDirectDefaults.makeDefaultApolloState(), {
					'agent_id': 8050,
					'hasPnr': true,
					'isPnrStored': true,
					'pcc': '2F3K',
					'recordLocator': 'XK7G76',
				}),
				'initialCommands': [
					{
						'cmd': '*R',
						'output': [
							'CREATED IN GDS DIRECT BY AKLESUNS',
							'XK7G76/WS QSBYC DPBVWS  AG 05578602 02APR',
							' 1.1UZUMAKI/NARUTO ',
							' 1 UA 613Y 25JUN SFOLAX HK1   630A  816A           TU  P',
							'FONE-SFOAS/800-750-2238 ASAP CUSTOMER SUPPORT',
							'TKTG-TAU/02APR',
							'*** LINEAR FARE DATA EXISTS *** >*LF· ',
							'ATFQ-OK/$B-*2F3K/TA2F3K/CUA/ET',
							' FQ-USD 901.40/USD 67.60US/USD 14.30XT/USD 983.30 - 2APR YAA0AFEY',
							'GFAX-SSRDOCSUAHK1/////10MAY90/M//UZUMMAKI/NARUTO-1UZUMAKI/NARUTO',
							'RMKS-GD-AKLESUNS/6206/LEAD-8013096 IN 2F3K',
							'><',
						].join('\n'),
					},
				],
				'performedCommands': [
					{
						'cmd': 'HB:FEX016 7289 106161',
						'output': [
							'>$EX NAME UZUMAKI/NARUTO                     PSGR  1/ 1',
							'FARE USD   901.40  TOTAL USD   983.30',
							'TX1 USD   67.60 US   TX2 USD   14.30 XT   TX3               ',
							'',
							'EXCHANGE TKTS ;..............-;...  CPN ALL',
							'TKT1;01672891061612 CPN;1... TKT2;.............. CPN;....',
							'COMM;.........  ORIG FOP;CK................. EVEN;.',
							'',
							'TTL VALUE OF EX TKTS USD;983.30.........ORIG BRD/OFF;SFO;LAX',
							'TX1 USD;67.60..;US   TX2 USD;14.30..;XT   TX3 USD;.......;..',
							'ORIG ISS;SFO....ORIG DATE;02APR19 ORIG IATA NBR;00000000 ',
							'ORIG TKT;0161111111111.-;...  ORIG INV NBR;.........',
							'PENALTY USD;............  COMM ON PENALTY;...........',
							'><',
						].join('\n'),
					},
					{
						cmd: '*HA',
						output: [
							'INVLD',
							'><',
						].join('\n'),
					},
				],
			},
		});

		list.push({
			'title': 'HB:FEX with MCO document number completion data',
			'input': {
				'cmdRequested': 'HB2:FEX',
			},
			'output': {
				'status': 'executed',
				'calledCommands': [
					{
						'cmd': 'HB2:FEX',
						'output': 'SEE MASK FORM BELOW',
					},
				],
				'actions': [
					{
						'type': 'displayExchangeMask',
						'data': {
							'mcoRows': [
								{
									'command': '*MCO2',
									'passengerName': 'ARTUS/KL',
									'documentNumber': '0065056180984',
									'issueDate': {'raw': '03APR19', 'parsed': '2019-04-03'},
									'amount': '100.00',
								},
							],
							'headerData': {
								'lastName': 'ARTUS',
								'firstName': 'KLESUN',
								'majorNumber': '1',
								'minorNumber': '1',
								'baseFareCurrency': 'USD',
								'baseFareAmount': '617.68',
								'netPriceCurrency': 'USD',
								'netPriceAmount': '678.30',
								'equivalentPart': '',
								'taxCurrency1': 'USD',
								'taxAmount1': '46.32',
								'taxCode1': 'US',
								'taxCurrency2': 'USD',
								'taxAmount2': '14.30',
								'taxCode2': 'XT',
								'taxCurrency3': undefined,
								'taxAmount3': undefined,
								'taxCode3': undefined,
								'exchangedTicketCurrency': 'USD',
							},
							'fields': [
								{'key': 'exchangedTicketNumber', 'value': '', 'enabled': true},
								{'key': 'exchangedTicketExtension', 'value': '', 'enabled': true},
								{'key': 'ticketNumber1', 'value': '', 'enabled': true},
								{'key': 'couponNumber1', 'value': '', 'enabled': true},
								{'key': 'ticketNumber2', 'value': '', 'enabled': true},
								{'key': 'couponNumber2', 'value': '', 'enabled': true},
								{'key': 'commission', 'value': '', 'enabled': true},
								{'key': 'originalFormOfPayment', 'value': '', 'enabled': true},
								{'key': 'evenIndicator', 'value': '', 'enabled': true},
								{'key': 'exchangedTicketTotalValue', 'value': '', 'enabled': true},
								{'key': 'originalBoardPoint', 'value': '', 'enabled': false},
								{'key': 'originalOffPoint', 'value': '', 'enabled': false},
								{'key': 'taxAmount1', 'value': '', 'enabled': true},
								{'key': 'taxCode1', 'value': '', 'enabled': true},
								{'key': 'taxAmount2', 'value': '', 'enabled': true},
								{'key': 'taxCode2', 'value': '', 'enabled': true},
								{'key': 'taxAmount3', 'value': '', 'enabled': true},
								{'key': 'taxCode3', 'value': '', 'enabled': true},
								{'key': 'originalIssuePoint', 'value': '', 'enabled': true},
								{'key': 'originalIssueDate', 'value': '', 'enabled': true},
								{'key': 'originalAgencyIata', 'value': '', 'enabled': false},
								{'key': 'originalTicketStar', 'value': '', 'enabled': true},
								{
									'key': 'originalTicketStarExtension',
									'value': '',
									'enabled': false,
								},
								{'key': 'originalInvoiceNumber', 'value': '', 'enabled': false},
								{'key': 'penaltyAmount', 'value': '', 'enabled': true},
								{'key': 'commOnPenaltyAmount', 'value': '', 'enabled': true},
							],
							'maskOutput': [
								'>$EX NAME ARTUS/KLESUN                       PSGR  1/ 1',
								'FARE USD   617.68  TOTAL USD   678.30',
								'TX1 USD   46.32 US   TX2 USD   14.30 XT   TX3               ',
								'',
								'EXCHANGE TKTS ;..............-;...  CPN ALL',
								'TKT1;.............. CPN;.... TKT2;.............. CPN;....',
								'COMM;.........  ORIG FOP;................... EVEN;.',
								'',
								'TTL VALUE OF EX TKTS USD;.............  ORIG BRD/OFF;...;...',
								'TX1 USD;.......;..   TX2 USD;.......;..   TX3 USD;.......;..',
								'ORIG ISS;...... ORIG DATE;....... ORIG IATA NBR;.........',
								'ORIG TKT;..............-;...  ORIG INV NBR;.........',
								'PENALTY USD;............  COMM ON PENALTY;...........',
								'><',
							].join('\n'),
						},
					},
				],
			},
			'sessionInfo': {
				'initialState': _.extend(GdsDirectDefaults.makeDefaultApolloState(), {
					'agent_id': 8050,
					'hasPnr': true,
					'isPnrStored': true,
					'pcc': '2F3K',
					'recordLocator': 'Q5FHPH',
				}),
				'initialCommands': [],
				'performedCommands': [
					{
						'cmd': '*R',
						'output': [
							'RICO@TEST',
							'Q5FHPH/WS QSBYC DPBVWS  AG 05578602 03APR',
							' 1.1BITCA/IURI  2.1ARTUS/KLESUN ',
							' 1 DL 585Y 25SEP SFOLAX HK2   615A  747A *         WE   E',
							'FONE-SFO1',
							'FOP:-AXXXXXXXXXXXX1052/D0223/*124259',
							'TKTG-T/QSB 03APR1437Z WS AG *',
							'*** TIN REMARKS EXIST *** >*T; ',
							'*** MISCELLANEOUS DOCUMENT DATA EXISTS *** >*MPD; ',
							'*** LINEAR FARE DATA EXISTS *** >*LF; ',
							'1/ATFQ-UTCC/$BN1/:N/Z0/FEX/ET/TA2F3K/CDL',
							' FQ-USD 617.68/USD 46.32US/USD 14.30XT/USD 678.30 - 3APR Y0',
							'2/ATFQ-UTCC/$BN2/:N/Z0/FEX/ET/TA2F3K/CDL',
							')><',
						].join('\n'),
					},
					{
						'cmd': 'MR',
						'output': [
							' FQ-USD 617.68/USD 46.32US/USD 14.30XT/USD 678.30 - 3APR Y0',
							'GFAX-SSRDOCSDLHK1/////10MAY90/M//RICO/SRICO-1BITCA/IURI',
							'   2 SSRDOCSDLHK1/////10MAY90/M//RICO/SRICO-1ARTUS/KLESUN',
							'   3 SSRADTK1VTODL BY 26AUG 2359 SFO OTHERWISE MAY BE XLD',
							'   4 SSRADTK1VTODL BY 26AUG FARE MAY NEED EARLIER TKT DTE',
							'RMKS-GD-RICO/5820 IN 2F3K',
							'ACKN-DL JLYTZO   03APR 1427',
							'><',
						].join('\n'),
					},
					{
						'cmd': 'HB2:FEX',
						'output': [
							'>$EX NAME ARTUS/KLESUN                       PSGR  1/ 1',
							'FARE USD   617.68  TOTAL USD   678.30',
							'TX1 USD   46.32 US   TX2 USD   14.30 XT   TX3               ',
							'',
							'EXCHANGE TKTS ;..............-;...  CPN ALL',
							'TKT1;.............. CPN;.... TKT2;.............. CPN;....',
							'COMM;.........  ORIG FOP;................... EVEN;.',
							'',
							'TTL VALUE OF EX TKTS USD;.............  ORIG BRD/OFF;...;...',
							'TX1 USD;.......;..   TX2 USD;.......;..   TX3 USD;.......;..',
							'ORIG ISS;...... ORIG DATE;....... ORIG IATA NBR;.........',
							'ORIG TKT;..............-;...  ORIG INV NBR;.........',
							'PENALTY USD;............  COMM ON PENALTY;...........',
							'><',
						].join('\n'),
						'duration': '1.634242412',
						'type': 'issueTickets',
						'scrolledCmd': 'HB2:FEX',
						'state': {
							'area': 'A',
							'pcc': '2F3K',
							'recordLocator': 'Q5FHPH',
							'canCreatePq': false,
							'pricingCmd': null,
							'hasPnr': true,
							'isPnrStored': true,
							'cmdType': 'issueTickets',
							'scrolledCmd': 'HB2:FEX',
						},
					},
					{
						'cmd': '*MPD',
						'output': [
							'*MPD             MISCELLANEOUS DOCUMENT LIST',
							'          NAME         DOCUMENT NBR   ISSUED       AMOUNT',
							'>*MCO1;   BITCA/IU    0065056180983   03APR19          100.00 ',
							'>*MCO2;   ARTUS/KL    0065056180984   03APR19          100.00 ',
							'END OF DISPLAY',
							'><',
						].join('\n'),
					},
					{
						'cmd': '*MCO2',
						'output': [
							'ERROR: FAKE OUTPUT FOR OLD TESTS COMPATIBILITY, MCO MASK NOT AVAILABLE',
							'><',
						].join('\n'),
					},
					{
						'cmd': '*HT',
						'output': [
							'ERROR: FAKE OUTPUT FOR OLD TESTS COMPATIBILITY',
							'><',
						].join('\n'),
					},
					{
						cmd: '*HA',
						output: [
							'INVLD',
							'><',
						].join('\n'),
					},
				],
			},
		});

		list.push({
			'title': 'HB:FEX with MCO document number completion data, multiple paxes with same last name',
			'input': {
				'cmdRequested': 'HB2:FEX',
			},
			'output': {
				'status': 'executed',
				'calledCommands': [
					{
						'cmd': 'HB2:FEX',
						'output': 'SEE MASK FORM BELOW',
					},
				],
				'actions': [
					{
						'type': 'displayExchangeMask',
						'data': {
							'mcoRows': [
								{
									'command': '*MCO2',
									'passengerName': 'BITCA/IU',
									'documentNumber': '0065056180986',
									'issueDate': {'raw': '04APR19', 'parsed': '2019-04-04'},
									'amount': '100.00',
									'fullData': {
										'passengerName': 'BITCA/IURI',
										'to': 'DL',
										'at': 'ATL',
										'validFor': 'SPLIT',
										'tourCode': '',
										'ticketNumber': '',
										'formOfPayment': {'raw': 'AXXXXXXXXXXXX1052/OK'},
										'expirationMonth': '02',
										'expirationYear': '23',
										'approvalCode': '109678',
										'commission': '0.00/',
										'taxAmount': '',
										'taxCode': '',
										'baseFare': {'currency': 'USD', 'amount': '100.00'},
										'fareEquivalent': null,
										'rateOfExchange': '',
										'endorsementBox': '',
										'remark1': '',
										'remark2': '',
										'validatingCarrier': 'DL',
										'issueNow': false,
									},
								},
							],
							'headerData': {
								'lastName': 'BITCA',
								'firstName': 'IURI',
								'majorNumber': '1',
								'minorNumber': '1',
								'baseFareCurrency': 'USD',
								'baseFareAmount': '617.68',
								'netPriceCurrency': 'USD',
								'netPriceAmount': '678.30',
								'equivalentPart': '',
								'taxCurrency1': 'USD',
								'taxAmount1': '46.32',
								'taxCode1': 'US',
								'taxCurrency2': 'USD',
								'taxAmount2': '14.30',
								'taxCode2': 'XT',
								'taxCurrency3': undefined,
								'taxAmount3': undefined,
								'taxCode3': undefined,
								'exchangedTicketCurrency': 'USD',
							},
							'fields': [
								{'key': 'exchangedTicketNumber', 'value': '', 'enabled': true},
								{'key': 'exchangedTicketExtension', 'value': '', 'enabled': true},
								{'key': 'ticketNumber1', 'value': '', 'enabled': true},
								{'key': 'couponNumber1', 'value': '', 'enabled': true},
								{'key': 'ticketNumber2', 'value': '', 'enabled': true},
								{'key': 'couponNumber2', 'value': '', 'enabled': true},
								{'key': 'commission', 'value': '', 'enabled': true},
								{'key': 'originalFormOfPayment', 'value': '', 'enabled': true},
								{'key': 'evenIndicator', 'value': '', 'enabled': true},
								{'key': 'exchangedTicketTotalValue', 'value': '', 'enabled': true},
								{'key': 'originalBoardPoint', 'value': '', 'enabled': false},
								{'key': 'originalOffPoint', 'value': '', 'enabled': false},
								{'key': 'taxAmount1', 'value': '', 'enabled': true},
								{'key': 'taxCode1', 'value': '', 'enabled': true},
								{'key': 'taxAmount2', 'value': '', 'enabled': true},
								{'key': 'taxCode2', 'value': '', 'enabled': true},
								{'key': 'taxAmount3', 'value': '', 'enabled': true},
								{'key': 'taxCode3', 'value': '', 'enabled': true},
								{'key': 'originalIssuePoint', 'value': '', 'enabled': true},
								{'key': 'originalIssueDate', 'value': '', 'enabled': true},
								{'key': 'originalAgencyIata', 'value': '', 'enabled': false},
								{'key': 'originalTicketStar', 'value': '', 'enabled': true},
								{
									'key': 'originalTicketStarExtension',
									'value': '',
									'enabled': false,
								},
								{'key': 'originalInvoiceNumber', 'value': '', 'enabled': false},
								{'key': 'penaltyAmount', 'value': '', 'enabled': true},
								{'key': 'commOnPenaltyAmount', 'value': '', 'enabled': true},
							],
							'maskOutput': [
								'>$EX NAME BITCA/IURI                         PSGR  1/ 1',
								'FARE USD   617.68  TOTAL USD   678.30',
								'TX1 USD   46.32 US   TX2 USD   14.30 XT   TX3               ',
								'',
								'EXCHANGE TKTS ;..............-;...  CPN ALL',
								'TKT1;.............. CPN;.... TKT2;.............. CPN;....',
								'COMM;.........  ORIG FOP;................... EVEN;.',
								'',
								'TTL VALUE OF EX TKTS USD;.............  ORIG BRD/OFF;...;...',
								'TX1 USD;.......;..   TX2 USD;.......;..   TX3 USD;.......;..',
								'ORIG ISS;...... ORIG DATE;....... ORIG IATA NBR;.........',
								'ORIG TKT;..............-;...  ORIG INV NBR;.........',
								'PENALTY USD;............  COMM ON PENALTY;...........',
								'><',
							].join('\n'),
						},
					},
				],
			},
			'sessionInfo': {
				'initialState': _.extend(GdsDirectDefaults.makeDefaultApolloState(), {
					'agent_id': 8050,
					'hasPnr': true,
					'isPnrStored': true,
					'pcc': '2F3K',
					'recordLocator': 'TM6S7O',
				}),
				'initialCommands': [],
				'performedCommands': [
					{
						'cmd': '*R',
						'output': [
							'CREATED IN GDS DIRECT BY RICO',
							'TM6S7O/WS QSBYC DPBVWS  AG 05578602 04APR',
							' 1.1ARTURS/KLESUNS  2.1BITCA/IURI ',
							' 1 DL2754Y 25OCT LAXSFO HK2  1000A 1146A *         FR   E',
							'FONE-SFO1',
							'FOP:-AXXXXXXXXXXXX1052/D0223/*109678',
							'TKTG-T/QSB 04APR1214Z WS AG *',
							'*** TIN REMARKS EXIST *** >*T; ',
							'*** MISCELLANEOUS DOCUMENT DATA EXISTS *** >*MPD; ',
							'*** LINEAR FARE DATA EXISTS *** >*LF; ',
							'1/ATFQ-UT/$BN1/-*2F3K/TA2F3K/CDL/ET',
							' FQ-USD 617.68/USD 46.32US/USD 14.30XT/USD 678.30 - 4APR Y0',
							'2/ATFQ-UT/$BN2/-*2F3K/TA2F3K/CDL/ET',
							')><',
						].join('\n'),
					},
					{
						'cmd': 'MR',
						'output': [
							' FQ-USD 617.68/USD 46.32US/USD 14.30XT/USD 678.30 - 4APR Y0',
							'GFAX-SSRDOCSDLHK1/////10MAY90/M//RICO/SRICO-1BITCA/IURI',
							'   2 SSRDOCSDLHK1/////10MAY90/M//RICO/SRICO-1BITCA/IURI',
							'   3 SSRDOCSDLHK1/////10MAY90/M//RICO/SRICO-1ARTURS/KLESUNS',
							'   4 SSRADTK1VTODL BY 25SEP 2359 SFO OTHERWISE MAY BE XLD',
							'   5 SSRADTK1VTODL BY 25SEP FARE MAY NEED EARLIER TKT DTE',
							'RMKS-GD-RICO/5820 IN 2F3K',
							'ACKN-DL GP87OI   04APR 1157',
							'><',
						].join('\n'),
					},
					{
						'cmd': 'HB2:FEX',
						'output': [
							'>$EX NAME BITCA/IURI                         PSGR  1/ 1',
							'FARE USD   617.68  TOTAL USD   678.30',
							'TX1 USD   46.32 US   TX2 USD   14.30 XT   TX3               ',
							'',
							'EXCHANGE TKTS ;..............-;...  CPN ALL',
							'TKT1;.............. CPN;.... TKT2;.............. CPN;....',
							'COMM;.........  ORIG FOP;................... EVEN;.',
							'',
							'TTL VALUE OF EX TKTS USD;.............  ORIG BRD/OFF;...;...',
							'TX1 USD;.......;..   TX2 USD;.......;..   TX3 USD;.......;..',
							'ORIG ISS;...... ORIG DATE;....... ORIG IATA NBR;.........',
							'ORIG TKT;..............-;...  ORIG INV NBR;.........',
							'PENALTY USD;............  COMM ON PENALTY;...........',
							'><',
						].join('\n'),
					},
					{
						'cmd': '*MPD',
						'output': [
							'*MPD             MISCELLANEOUS DOCUMENT LIST',
							'          NAME         DOCUMENT NBR   ISSUED       AMOUNT',
							'>*MCO1;   BITCA/IU    0065056180985   04APR19          100.00 ',
							'>*MCO2;   BITCA/IU    0065056180986   04APR19          100.00 ',
							'>*MCO3;   LONGLONG    0065056180987   04APR19          100.00 ',
							'END OF DISPLAY',
							'><',
						].join('\n'),
					},
					{
						'cmd': '*MCO1',
						'output': [
							'>HHMCU1           *** MISC CHARGE ORDER ***',
							' PASSENGER NAME;BITCA/IUBELY............................',
							' TO;DL...................................... AT;ATL............',
							' VALID FOR;SPLIT...............................................',
							' TOUR CODE;............... RELATED TKT NBR;.............',
							' FOP;AXXXXXXXXXXXX1052/OK......................................',
							' EXP DATE;0223 APVL CODE;109678 COMM;0.00/... TAX;........-;..',
							' AMOUNT;100.00..-;USD EQUIV ;........-;... BSR;..........',
							' END BOX;......................................................',
							' REMARK1;..............................................',
							' REMARK2;......................................................',
							' VALIDATING CARRIER;DL                  ISSUE NOW;.',
							'><',
						].join('\n'),
					},
					{
						'cmd': '*MCO2',
						'output': [
							'>HHMCU2           *** MISC CHARGE ORDER ***',
							' PASSENGER NAME;BITCA/IURI..............................',
							' TO;DL...................................... AT;ATL............',
							' VALID FOR;SPLIT...............................................',
							' TOUR CODE;............... RELATED TKT NBR;.............',
							' FOP;AXXXXXXXXXXXX1052/OK......................................',
							' EXP DATE;0223 APVL CODE;109678 COMM;0.00/... TAX;........-;..',
							' AMOUNT;100.00..-;USD EQUIV ;........-;... BSR;..........',
							' END BOX;......................................................',
							' REMARK1;..............................................',
							' REMARK2;......................................................',
							' VALIDATING CARRIER;DL                  ISSUE NOW;.',
							'><',
						].join('\n'),
					},
					{
						'cmd': '*HT',
						'output': [
							'ERROR: FAKE OUTPUT FOR OLD TESTS COMPATIBILITY',
							'><',
						].join('\n'),
					},
					{
						cmd: '*HA',
						output: [
							'INVLD',
							'><',
						].join('\n'),
					},
				],
			},
		});

		// note that *MCO1 would be called in real life, but test does not
		// fail because it catches the exception thrown by AnyGdsSession.js
		list.push({
			'title': 'HB:FEX failed to provide *MPD data',
			'input': {
				'cmdRequested': 'HB:FEX',
			},
			'output': {
				'status': 'executed',
				'calledCommands': [
					{
						'cmd': 'HB:FEX',
						'output': 'SEE MASK FORM BELOW',
					},
				],
				'actions': [
					{
						'type': 'displayExchangeMask',
						'data': {
							'mcoRows': [
								{
									'command': '*MCO1',
									'passengerName': 'MACABENT',
									'documentNumber': '9885056203638',
									'issueDate': {'raw': '04APR19'},
									'amount': '640.73',
								},
							],
							'headerData': {
								'lastName': 'MACABENTA',
								'firstName': 'ANTONIOJR INAY',
							},
							'fields': [
								{'key': 'exchangedTicketNumber', 'value': '', 'enabled': true},
								{'key': 'exchangedTicketExtension', 'value': '', 'enabled': true},
								{'key': 'ticketNumber1', 'value': '', 'enabled': true},
								{'key': 'couponNumber1', 'value': '', 'enabled': true},
								{'key': 'ticketNumber2', 'value': '', 'enabled': true},
								{'key': 'couponNumber2', 'value': '', 'enabled': true},
								{'key': 'commission', 'value': '', 'enabled': true},
								{'key': 'originalFormOfPayment', 'value': '', 'enabled': true},
								{'key': 'evenIndicator', 'value': '', 'enabled': true},
								{'key': 'exchangedTicketTotalValue', 'value': '', 'enabled': true},
								{'key': 'originalBoardPoint', 'value': '', 'enabled': false},
								{'key': 'originalOffPoint', 'value': '', 'enabled': false},
								{'key': 'taxAmount1', 'value': '', 'enabled': true},
								{'key': 'taxCode1', 'value': '', 'enabled': true},
								{'key': 'taxAmount2', 'value': '', 'enabled': true},
								{'key': 'taxCode2', 'value': '', 'enabled': true},
								{'key': 'taxAmount3', 'value': '', 'enabled': true},
								{'key': 'taxCode3', 'value': '', 'enabled': true},
								{'key': 'originalIssuePoint', 'value': '', 'enabled': true},
								{'key': 'originalIssueDate', 'value': '', 'enabled': true},
								{'key': 'originalAgencyIata', 'value': '', 'enabled': false},
								{'key': 'originalTicketStar', 'value': '', 'enabled': true},
								{
									'key': 'originalTicketStarExtension',
									'value': '',
									'enabled': false,
								},
								{'key': 'originalInvoiceNumber', 'value': '', 'enabled': false},
								{'key': 'penaltyAmount', 'value': '', 'enabled': true},
								{'key': 'commOnPenaltyAmount', 'value': '', 'enabled': true},
							],
							'maskOutput': [
								'>$EX NAME MACABENTA/ANTONIOJR INAY           PSGR  1/ 1',
								'FARE USD   440.00  TOTAL USD   655.73',
								'TX1 USD   37.20 US   TX2 USD  178.53 XT   TX3               ',
								'',
								'EXCHANGE TKTS ;..............-;...  CPN ALL',
								'TKT1;.............. CPN;.... TKT2;.............. CPN;....',
								'COMM;.........  ORIG FOP;................... EVEN;.',
								'',
								'TTL VALUE OF EX TKTS USD;.............  ORIG BRD/OFF;...;...',
								'TX1 USD;.......;..   TX2 USD;.......;..   TX3 USD;.......;..',
								'ORIG ISS;...... ORIG DATE;....... ORIG IATA NBR;.........',
								'ORIG TKT;..............-;...  ORIG INV NBR;.........',
								'PENALTY USD;............  COMM ON PENALTY;...........',
								'><',
							].join('\n'),
						},
					},
				],
			},
			'sessionInfo': {
				'initialState': _.extend(GdsDirectDefaults.makeDefaultApolloState(), {
					'agent_id': 8050,
					'hasPnr': true,
					'isPnrStored': true,
					'pcc': '1O3K',
					'recordLocator': 'WT0BQY',
				}),
				'initialCommands': [],
				'performedCommands': [
					{
						'cmd': '*R',
						'output': [
							'RICO',
							'2G55 - INTERNATIONAL TVL NETWOR SFO',
							'WT0BQY/WS QSBYC DPBVWS  AG 05578602 04APR',
							' 1.1MACABENTA/ANTONIOJR INAY ',
							' 1 OZ 201W 01DEC LAXICN HK1  1100A  530P|*      SU/MO   E',
							' 2 OZ 703W 02DEC ICNMNL HK1   750P 1100P *         MO   E',
							' 3 OZ 702V 29DEC MNLICN HK1  1205P  440P *         SU   E',
							' 4 OZ 204W 29DEC ICNLAX HK1   840P  250P *         SU   E',
							'FONE-SFOAS/800-750-2238 ASAP CUSTOMER SUPPORT',
							'FOP:-VIXXXXXXXXXXXX6018/D0423/*04711C',
							'TKTG-T/QSB 04APR1818Z WS AG *',
							'*** TIN REMARKS EXIST *** >*T; ',
							'*** MISCELLANEOUS DOCUMENT DATA EXISTS *** >*MPD; ',
							')><',
						].join('\n'),
					},
					{
						'cmd': 'MR',
						'output': [
							'*** LINEAR FARE DATA EXISTS *** >*LF; ',
							'ATFQ-OK/$B/:N/IT9ULDD1WB/Z5/ET/TA1O3K/COZ',
							' FQ-USD 440.00/USD 37.20US/USD 178.53XT/USD 655.73 - 4APR WLXAUS14.WLXAUS14.WLXAUS14.WLXAUS14',
							'GFAX-SSROTHS1V OZ RSVN IS 0428-9848',
							'   2 SSRADTK1VTOOZ BY 07APR 1100 OTHERWISE WILL BE XLD',
							'   3 SSRCTCEOZHK1/MACABENTA..JUN//YAHOO.COM-1MACABENTA/ANTONIOJR INAY',
							'   4 SSRCTCMOZHK1/2133217785-1MACABENTA/ANTONIOJR INAY',
							'   5 SSRDOCSOZHK1/////18NOV59/M//MACABENTA/ANTONIOJR/INAY-1MACABENTA/ANTONIOJR INAY',
							'RMKS-GD-GINGER/101193/FOR GINGER/101193/LEAD-11092490 IN 2G55',
							'ACKN-1A OY4PP9   04APR 1712',
							')><',
						].join('\n'),
					},
					{
						'cmd': 'MR',
						'output': [
							'   2 1A OY4PP9   04APR 1712',
							'><',
						].join('\n'),
					},
					{
						'cmd': 'HB:FEX',
						'output': [
							'>$EX NAME MACABENTA/ANTONIOJR INAY           PSGR  1/ 1',
							'FARE USD   440.00  TOTAL USD   655.73',
							'TX1 USD   37.20 US   TX2 USD  178.53 XT   TX3               ',
							'',
							'EXCHANGE TKTS ;..............-;...  CPN ALL',
							'TKT1;.............. CPN;.... TKT2;.............. CPN;....',
							'COMM;.........  ORIG FOP;................... EVEN;.',
							'',
							'TTL VALUE OF EX TKTS USD;.............  ORIG BRD/OFF;...;...',
							'TX1 USD;.......;..   TX2 USD;.......;..   TX3 USD;.......;..',
							'ORIG ISS;...... ORIG DATE;....... ORIG IATA NBR;.........',
							'ORIG TKT;..............-;...  ORIG INV NBR;.........',
							'PENALTY USD;............  COMM ON PENALTY;...........',
							'><',
						].join('\n'),
					},
					{
						'cmd': '*MPD',
						'output': [
							'*MPD             MISCELLANEOUS DOCUMENT LIST',
							'          NAME         DOCUMENT NBR   ISSUED       AMOUNT',
							'>*MCO1;   MACABENT    9885056203638   04APR19          640.73 ',
							'END OF DISPLAY',
							'><',
						].join('\n'),
					},
					{
						'cmd': '*MCO1',
						'output': [
							'ERROR: FAKE OUTPUT FOR OLD TESTS COMPATIBILITY, MCO MASK NOT AVAILABLE',
							'><',
						].join('\n'),
					},
					{
						'cmd': '*HT',
						'output': [
							'ERROR: FAKE OUTPUT FOR OLD TESTS COMPATIBILITY',
							'><',
						].join('\n'),
					},
					{
						cmd: '*HA',
						output: [
							'INVLD',
							'><',
						].join('\n'),
					},
				],
			},
		});

		list.push({
			'input': {
				'title': 'should check that ATFQ only has 1 passenger before calling HB:FEX',
				'cmdRequested': 'HB:FEX',
			},
			'output': {
				'status': 'forbidden',
				'userMessages': ['Error: Multiple passengers (2) in ATFQ #1 not allowed for HB:FEX'],
			},
			'sessionInfo': {
				'initialState': _.extend(GdsDirectDefaults.makeDefaultApolloState(), {
					'agent_id': 8050,
					'hasPnr': true,
					'isPnrStored': true,
					'pcc': '1O3K',
					'recordLocator': 'PVNNMP',
				}),
				'initialCommands': [],
				'performedCommands': [
					{
						'cmd': '*R',
						'output': [
							'PANDAREN',
							'2F3K - INTERNATIONAL TRAVEL NET SFO',
							'PVNNMP/WS QSBYC DPBVWS  AG 05578602 07MAY',
							' 1.1MCHARO/LAILA MGHOI  2.1SAMB/MAMADOU ASSANE ',
							' 1 KQ   3Q 03JUL JFKNBO HK2  1255P 1025A|*      WE/TH   E',
							' 2 KQ8604Q 04JUL NBOMBA HK2  1225P  130P *         TH   E',
							'         OPERATED BY JAMBOJET',
							' 3 KQ 611Q 19JUL MBANBO HK2   640P  740P *         FR   E  1',
							' 4 KQ   2Q 19JUL NBOJFK HK2  1055P  655A|*      FR/SA   E  1',
							'FONE-SFOAS/800-750-2238 ASAP CUSTOMER SUPPORT',
							'FOP:-VIXXXXXXXXXXXX8932/D0122/*02273C',
							'TKTG-T/QSB 07MAY1801Z WS AG *',
							'*** TIN REMARKS EXIST *** >*T; ',
							')><',
						].join('\n'),
					},
					{
						'cmd': 'MR',
						'output': [
							'*** MISCELLANEOUS DOCUMENT DATA EXISTS *** >*MPD; ',
							'*** LINEAR FARE DATA EXISTS *** >*LF; ',
							'ATFQ-OK/$B/:N/ITKQCON001/Z3/ET/TA1O3K/CKQ',
							' FQ-USD 1710.00/USD 74.40US/USD 1213.66XT/USD 2998.06 - 7MAY QH3RUSW3.QH3RUSW3.QH3RUSW3.QH3RUSW3/QH3RUSW3.QH3RUSW3.QH3RUSW3.QH3RUSW3',
							'GFAX-SSRADTK1VTOKQ BY 10MAY19/2300Z OTHERWISE WILL BE XXLD',
							'   2 SSRCTCEKQHK1/KANUINKE//YAHOO.COM-1MCHARO/LAILA MGHOI',
							'   3 SSRCTCMKQHK1/3472847139-1MCHARO/LAILA MGHOI',
							'   4 SSRCTCMKQHK1/3475410721-1SAMB/MAMADOU ASSANE',
							'   5 SSRDOCSKQHK1/////21JUN77/F//MCHARO/LAILA/MGHOI-1MCHARO/LAILA MGHOI',
							'   6 SSRDOCSKQHK1/////05FEB69/M//SAMB/MAMADOU/ASSANE-1SAMB/MAMAD)><',
						].join('\n'),
					},
					{
						'cmd': 'MR',
						'output': [
							'OU ASSANE',
							'RMKS-GD-RANGER/102053/FOR RANGER/102053/LEAD-11395374 IN 2F3K',
							'ACKN-1A QZGQML   07MAY 1640',
							'   2 1A QZGQML   07MAY 1640',
							'><',
						].join('\n'),
					},
				],
			},
		});

		list.push({
			title: 'example of original issue in UTC is not same as in PCC timezone',
			input: {
				cmdRequested: 'HB:FEX',
				baseDate: '2019-08-29 00:00:00',
			},
			output: {
				status: 'executed',
				actions: [{
					type: 'displayExchangeMask',
					data: {
						'currentPos': 'ATL',
						'mcoRows': [
							{
								'command': '*MCO1',
								'passengerName': 'EGBUHO/S',
								'documentNumber': '0065056248761',
								'issueDate': {'raw':'24MAY19','parsed':'2019-05-24'},
								'amount': '1385.30',
							},
						],
						'htRows': [
							{isActive: true, ticketNumber: '0067401158461', transactionDt: {parsed: '05-24 05:31'}},
							{isActive: false, ticketNumber: '0065056248761', transactionDt: {parsed: '05-24 04:45'}},
						],
					},
				}],
			},
			sessionInfo: {
				'initialState': _.extend(GdsDirectDefaults.makeDefaultApolloState(), {
					'agent_id': 8050,
					'hasPnr': true,
					'isPnrStored': true,
					'pcc': '2G8P',
					'recordLocator': 'PBS98E',
				}),
				'initialCommands': [
					{
						'cmd': '*R',
						'output': [
							'** THIS PNR IS CURRENTLY IN USE **',
							'JUMER',
							'PBS98E/WS QSBYC DPBVWS  AG 23854526 23MAY',
							' 1.1EGBUHO/SOLOMONDAVID OGADINMA ',
							' 1 DL 118X 14JUL LAXCDG HK1  1200N  755A|*      SU/MO   E',
							' 2 AF 104R 15JUL CDGLOS HK1   215P  735P *         MO   E',
							' 3 KL 588N 23JUL LOSAMS HK1   945P  545A|*      TU/WE   E  1',
							' 4 KL6035N 24JUL AMSDTW HK1   920A 1137A *         WE   E  1',
							'         OPERATED BY DELTA AIR LINES',
							' 5 DL1659T 24JUL DTWLAX HK1   212P  355P *         WE   E',
							'*** PROFILE ASSOCIATIONS EXIST *** >*PA; ',
							'FONE-SFOAS/800-750-2238 ASAP CUSTOMER SUPPORT',
							'   2 ATLAS/212-481-5516-JUMER',
							')><',
						].join('\n'),
					},
					{
						'cmd': 'MR',
						'output': [
							'   3 SFOR/800-750-2238-ITN',
							'ADRS-INTERNATIONAL TRAVEL NETWORK@100 PINE STREET@SUITE 1925@SAN FRANCISCO CA Z/94111',
							'FOP:-CAXXXXXXXXXXXX6695/D1222/*25767B',
							'TKTG-T/QSB 24MAY0445Z WS AG *',
							'*** TIN REMARKS EXIST *** >*T; ',
							'*** MISCELLANEOUS DOCUMENT DATA EXISTS *** >*MPD; ',
							'*** LINEAR FARE DATA EXISTS *** >*LF; ',
							'ATFQ-OK/$B/:N/Z8/ET/TA2G8P/CDL',
							' FQ-USD 788.00/USD 37.20US/USD 576.13XT/USD 1401.33 - 23MAY XH5L06M6.XH5L06M6.NH5L06M6.NH5L06M6.NH5L06M6',
							'GFAX-SSRADTK1VTOAF BY 26MAY 1700 OTHERWISE WILL BE XLD',
							'   2 SSRADTK1VTOKL BY 27MAY19/0600Z OTHERWISE WILL BE XXLD',
							')><',
						].join('\n'),
					},
					{
						'cmd': 'MR',
						'output': [
							'   3 SSRCTCEDLHK1/SEGBUHO//YAHOO.COM-1EGBUHO/SOLOMONDAVID OGADINMA',
							'   4 SSRCTCEAFHK1/SEGBUHO//YAHOO.COM-1EGBUHO/SOLOMONDAVID OGADINMA',
							'   5 SSRCTCEKLHK1/SEGBUHO//YAHOO.COM-1EGBUHO/SOLOMONDAVID OGADINMA',
							'   6 SSRCTCMDLHK1/15622858528-1EGBUHO/SOLOMONDAVID OGADINMA',
							'   7 SSRCTCMAFHK1/15622858528-1EGBUHO/SOLOMONDAVID OGADINMA',
							'   8 SSRCTCMKLHK1/15622858528-1EGBUHO/SOLOMONDAVID OGADINMA',
							'   9 SSRDOCSDLHK1/////06JAN53/M//EGBUHO/SOLOMONDAVID/OGADINMA-1EGBUHO/SOLOMONDAVID OGADINMA',
							'  10 SSRDOCSAFHK1/////06JAN53/M//EGBUHO/SOLOMONDAVID/OGADINMA-1EGBUHO/SOLOMONDAVID OGADINMA',
							')><',
						].join('\n'),
					},
					{
						'cmd': 'MR',
						'output': [
							'  11 SSRDOCSKLHK1/////06JAN53/M//EGBUHO/SOLOMONDAVID/OGADINMA-1EGBUHO/SOLOMONDAVID OGADINMA',
							'  12 SSRADTK1VTODL BY 26JUN 2359 SFO OTHERWISE MAY BE XLD',
							'  13 SSRADTK1VTODL BY 26JUN FARE MAY NEED EARLIER TKT DTE',
							'RMKS-GD-SUSAN/22728/FOR SUSAN/22728/LEAD-11786354 IN 2G2H',
							'TRMK-AN8007502041',
							'   2 DI-BR2',
							'   3 DI-UD35',
							'   4 CA ACCT-8007502041',
							'   5 UD8 0',
							'   6 UD1 P',
							'ACKN-DL G5GHKW   23MAY 2342',
							'   2 1A KGJAON   23MAY 2342',
							')><',
						].join('\n'),
					},
					{
						'cmd': 'MR',
						'output': [
							'   3 1A KGJAON   23MAY 2342',
							'><',
						].join('\n'),
					},
				],
				'performedCommands': [
					{
						'cmd': 'HB:FEX',
						'output': [
							'>$EX NAME EGBUHO/SOLOMONDAVID OGADINMA       PSGR  1/ 1',
							'FARE USD   788.00  TOTAL USD  1401.33',
							'TX1 USD   37.20 US   TX2 USD  576.13 XT   TX3               ',
							'',
							'EXCHANGE TKTS ;..............-;...  CPN ALL',
							'TKT1;.............. CPN;.... TKT2;.............. CPN;....',
							'COMM;.........  ORIG FOP;................... EVEN;.',
							'',
							'TTL VALUE OF EX TKTS USD;.............  ORIG BRD/OFF;...;...',
							'TX1 USD;.......;..   TX2 USD;.......;..   TX3 USD;.......;..',
							'ORIG ISS;...... ORIG DATE;....... ORIG IATA NBR;.........',
							'ORIG TKT;..............-;...  ORIG INV NBR;.........',
							'PENALTY USD;............  COMM ON PENALTY;...........',
							'><',
						].join('\n'),
					},
					{
						'cmd': '*MPD',
						'output': [
							'*MPD             MISCELLANEOUS DOCUMENT LIST',
							'          NAME         DOCUMENT NBR   ISSUED       AMOUNT',
							'>*MCO1;   EGBUHO/S    0065056248761   24MAY19         1385.30 ',
							'END OF DISPLAY',
							'><',
						].join('\n'),
					},
					{
						'cmd': '*MCO1',
						'output': [
							'>HHMCU1           *** MISC CHARGE ORDER ***',
							' PASSENGER NAME;EGBUHO/SOLOMONDAVID OGADINMA............',
							' TO;DL...................................... AT;ATL............',
							' VALID FOR;SPLIT...............................................',
							' TOUR CODE;............... RELATED TKT NBR;.............',
							' FOP;CAXXXXXXXXXXXX6695/OK.....................................',
							' EXP DATE;1222 APVL CODE;25767B COMM;0.00/... TAX;........-;..',
							' AMOUNT;1385.30.-;USD EQUIV ;........-;... BSR;..........',
							' END BOX;......................................................',
							' REMARK1;..............................................',
							' REMARK2;......................................................',
							' VALIDATING CARRIER;DL                  ISSUE NOW;.',
							'><',
						].join('\n'),
					},
					{
						'cmd': '*HT',
						'output': [
							'** CURRENT TIN DATA **',
							'EGBUHO/SOLOMON-00000000-01/0067401158461-462/EZ0002371-USD/1401.33/TE/24MAY0531Z',
							'** HISTORY TIN DATA **',
							'XK EGBUHO/SOLOMON-00011736-37/0065056248761/EZ0002367-USD/1385.30/24MAY0445Z',
							'><',
						].join('\n'),
					},
					{
						cmd: '*HA',
						output: [
							'     *****  AIR  HISTORY  *****',
							'HS JL  66 V09JAN NRTSAN NN/HK2   505P  955A *       1',
							'HS JL 746 V09JAN MNLNRT NN/HK2   940A  250P *       1',
							'RCVD-NIXON/ZDPBVWS -CR- QSB/2G8P/1V AG WS 10AUG0428Z',
							'><',
						].join('\n'),
					},
				],
			},
		});

		list.push({
			title: 'Return correct date values in mco response in case if date in issuing pcc is different because of timezones',
			input: {
				cmdRequested: 'HB1:FEX',
			},
			output: {
				calledCommands: [{
					cmd: 'HB1:FEX',
					output: 'SEE MASK FORM BELOW',
				}],
				actions: [{
					type: 'displayExchangeMask',
					data: {
						mcoRows: [{
							issueDate: {
								raw: '09AUG18',
								parsed: '2018-08-09',
							},
						}],
					},
				}],
			},
			sessionInfo: {
				initialState: _.extend(GdsDirectDefaults.makeDefaultApolloState(), {
					'agent_id': 8050,
					'hasPnr': true,
					'isPnrStored': true,
					'pcc': '2G8P',
					'recordLocator': 'NL1KSY',
				}),
				initialCommands: [{
					cmd: '*NL1KSY',
					output: [
						'JUMER',
						'NL1KSY/WS QSBYC DPBVWS  AG 05578602 09AUG',
						' 1.1BOWMAN/ANA CRISTINA  2.1BOWMAN/EMILY FRANCES ',
						' 1 JL 746V 09JAN MNLNRT HK2   940A  250P *         TH   E  1',
						' 2 JL  66V 09JAN NRTSAN HK2   505P  955A *         TH   E  1',
						'*** PROFILE ASSOCIATIONS EXIST *** >*PA; ',
						'FONE-SFOAS/800-750-2238 ASAP CUSTOMER SUPPORT',
						'   2 ATLAS/212-481-5516-JUMER',
						'   3 SFOR/800-750-2238-ITN',
						'ADRS-INTERNATIONAL TRAVEL NETWORK@100 PINE STREET@SUITE 1925@SAN FRANCISCO CA Z/94111',
						'FOP:-VIXXXXXXXXXXXX0026/D1223/*01779C',
						'TKTG-T/QSB 10AUG0502Z WS AG *',
						')><',
					].join('\n'),
				}],
				performedCommands: [{
					cmd: '*R',
					output: [
						'JUMER',
						'NL1KSY/WS QSBYC DPBVWS  AG 05578602 09AUG',
						' 1.1BOWMAN/ANA CRISTINA  2.1BOWMAN/EMILY FRANCES ',
						' 1 JL 746V 09JAN MNLNRT HK2   940A  250P *         TH   E  1',
						' 2 JL  66V 09JAN NRTSAN HK2   505P  955A *         TH   E  1',
						'*** PROFILE ASSOCIATIONS EXIST *** &gt;*PA; ',
						'FONE-SFOAS/800-750-2238 ASAP CUSTOMER SUPPORT',
						'   2 ATLAS/212-481-5516-JUMER',
						'   3 SFOR/800-750-2238-ITN',
						'ADRS-INTERNATIONAL TRAVEL NETWORK@100 PINE STREET@SUITE 1925@SAN FRANCISCO CA Z/94111',
						'FOP:-VIXXXXXXXXXXXX0026/D1223/*01779C',
						'TKTG-T/QSB 10AUG0502Z WS AG *',
						')><',
					].join('\n'),
				}, {
					cmd: 'MR',
					output: [
						'*** TIN REMARKS EXIST *** >*T; ',
						'*** MISCELLANEOUS DOCUMENT DATA EXISTS *** >*MPD; ',
						'*** LINEAR FARE DATA EXISTS *** >*LF; ',
						'1/ATFQ-OK/$BN1/:N/ITPJBTL/Z4/ET/TA2G8P/CJL',
						' FQ-USD 793.00/USD 18.60US/USD 88.53XT/USD 900.13 - 9AUG VNE00YN0.VNE00YN0',
						'2/ATFQ-OK/$BN2/:N/ITPJBTL/Z4/ET/TA2G8P/CJL',
						' FQ-USD 793.00/USD 18.60US/USD 88.53XT/USD 900.13 - 9AUG VNE00YN0.VNE00YN0',
						'GFAX-SSRADTK1VTOJL BY 16AUG 2359 SFO TIME ZONE OTHERWISE WILL BE XLD',
						'   2 SSRSFMLJLKK01 MNLNRT 0746V 09JAN-1BOWMAN/ANA CRISTINA ',
						'   3 SSRSFMLJLKK01 NRTSAN 0066V 09JAN-1BOWMAN/ANA CRISTINA ',
						')><',
					].join('\n'),
				}, {
					cmd: 'MR',
					output: [
						'   4 SSRVGMLJLKK01 MNLNRT 0746V 09JAN-1BOWMAN/EMILY FRANCES ',
						'   5 SSRVGMLJLKK01 NRTSAN 0066V 09JAN-1BOWMAN/EMILY FRANCES ',
						'   6 SSRCTCEJLHK1/ACBOWMAN2014//GMAIL.COM-1BOWMAN/ANA CRISTINA',
						'   7 SSRCTCEJLHK1/EBOWMAN1912//GMAIL.COM-1BOWMAN/EMILY FRANCES',
						'   8 SSRCTCMJLHK1/0013033789870-1BOWMAN/ANA CRISTINA',
						'   9 SSRCTCMJLHK1/0017208911557-1BOWMAN/EMILY FRANCES',
						'  10 SSRDOCSJLHK1/////21JUN62/F//BOWMAN/ANA/CRISTINA-1BOWMAN/ANA CRISTINA',
						'  11 SSRDOCSJLHK1/////11MAR96/F//BOWMAN/EMILY/FRANCES-1BOWMAN/EMILY FRANCES',
						'RMKS-GD-NIXON/101608/FOR NIXON/101608/LEAD-12618152 IN 2F3K',
						'TRMK-AN8007502041',
						'   2 DI-UD35',
						')><',
					].join('\n'),
				}, {
					cmd: 'MR',
					output: [
						'   3 CA ACCT-8007502041',
						'   4 UD8 0',
						'   5 UD1 P',
						'   6 UD10 SPLIT',
						'ACKN-1A JHNVIE   10AUG 0428',
						'   2 1A JHNVIE   10AUG 0428',
						'><',
					].join('\n'),
				}, {
					cmd: 'HB1:FEX',
					output: [
						'>$EX NAME BOWMAN/ANA CRISTINA                PSGR  1/ 1',
						'FARE USD   793.00  TOTAL USD   900.13',
						'TX1 USD   18.60 US   TX2 USD   88.53 XT   TX3               ',
						'',
						'EXCHANGE TKTS ;..............-;...  CPN ALL',
						'TKT1;.............. CPN;.... TKT2;.............. CPN;....',
						'COMM;.........  ORIG FOP;................... EVEN;.',
						'',
						'TTL VALUE OF EX TKTS USD;.............  ORIG BRD/OFF;...;...',
						'TX1 USD;.......;..   TX2 USD;.......;..   TX3 USD;.......;..',
						'ORIG ISS;...... ORIG DATE;....... ORIG IATA NBR;.........',
						'ORIG TKT;..............-;...  ORIG INV NBR;.........',
						'PENALTY USD;............  COMM ON PENALTY;...........',
						'><',
					].join('\n'),
				}, {
					cmd: '*MPD',
					output: [
						'*MPD             MISCELLANEOUS DOCUMENT LIST',
						'          NAME         DOCUMENT NBR   ISSUED       AMOUNT',
						'>*MCO1;   BOWMAN/A    1315056284699   10AUG19          869.03 ',
						'>*MCO2;   BOWMAN/E    1315056284700   10AUG19          869.03 ',
						'END OF DISPLAY',
						'><',
					].join('\n'),
				}, {
					cmd: '*MCO1',
					output: [
						'>HHMCU1           *** MISC CHARGE ORDER ***',
						' PASSENGER NAME;BOWMAN/ANA CRISTINA.....................',
						' TO;JL...................................... AT;HND............',
						' VALID FOR;SPLIT...............................................',
						' TOUR CODE;............... RELATED TKT NBR;.............',
						' FOP;VIXXXXXXXXXXXX0026/OK.....................................',
						' EXP DATE;1223 APVL CODE;01779C COMM;0.00/... TAX;........-;..',
						' AMOUNT;869.03..-;USD EQUIV ;........-;... BSR;..........',
						' END BOX;......................................................',
						' REMARK1;..............................................',
						' REMARK2;......................................................',
						' VALIDATING CARRIER;JL                  ISSUE NOW;.',
						'><',
					].join('\n'),
				}, {
					cmd: '*HT',
					output: [
						'** CURRENT TIN DATA **',
						'BOWMAN/EMILYF-00012774-75/1315056284700/EZ0102329-USD/869.03/10AUG0902Z',
						'** HISTORY TIN DATA **',
						'XK BOWMAN/ANACRI-00012772-73/1315056284699/EZ0102328-USD/869.03/10AUG0502Z',
						'><',
					].join('\n'),
				}, {
					cmd: '*HA',
					output: [
						'     *****  AIR  HISTORY  *****',
						'HS JL  66 V09JAN NRTSAN NN/HK2   505P  955A *       1',
						'HS JL 746 V09JAN MNLNRT NN/HK2   940A  250P *       1',
						'RCVD-NIXON/ZDPBVWS -CR- QSB/2F3K/1V AG WS 10AUG0428Z',
						'><',
					].join('\n'),
				}],
			},
		});

		list.push({
			title: 'Middle name too long, truncated even in HB:FEX screen',
			input: {
				cmdRequested: 'HB:FEX',
				baseDate: '2019-09-30 20:26:00',
			},
			output: {
				calledCommands: [{
					cmd: 'HB:FEX',
					output: 'SEE MASK FORM BELOW',
				}],
				actions: [
					{
						type: 'displayExchangeMask',
						data: {
							mcoRows: [
								{
									'command': '*MCO1',
									'passengerName': 'MONTROPE',
									'documentNumber': '2305056297697',
									'issueDate': {'raw': '30SEP19', 'parsed': '2019-09-30'},
									'amount': '370.53',
								},
							],
						},
					},
				],
			},
			sessionInfo: {
				initialState: {
					...GdsDirectDefaults.makeDefaultApolloState(),
					'agent_id': 5820,
					'hasPnr': true,
					'isPnrStored': true,
					'pcc': '1O3K',
					'recordLocator': 'QTMQ77',
				},
				initialCommands: [
					{
						"cmd": "*R",
						"output": [
							"** THIS PNR IS CURRENTLY IN USE **",
							"PANDAREN",
							"2F3K - INTERNATIONAL TRAVEL NET SFO",
							"QTMQ77/WS QSBYC DPBVWS  AG 05578602 30SEP",
							" 1.1MONTROPEZRUBIO/ORIETTA DE LOS ANGELES ",
							" 1 CM 229L 12FEB ORDPTY HK1   145P  816P *         WE   E  1",
							" 2 CM 635L 12FEB PTYBAQ HK1   948P 1101P *         WE   E  1",
							" 3 CM 674L 03MAR BAQPTY HK1   124P  247P *         TU   E  2",
							" 4 CM 235L 03MAR PTYORD HK1   636P 1115P *         TU   E  2",
							" 5 OTH ZO GK1  XXX 30JUL-PRESERVEPNR",
							"FONE-SFOAS/800-750-2238 ASAP CUSTOMER SUPPORT",
							"FOP:-VIXXXXXXXXXXXX1475/D1022/*510331",
							"TKTG-T/QSB 30SEP2021Z WS AG **ELECTRONIC DATA EXISTS** >*HTE;",
							")><",
						].join("\n"),
					},
					{
						"cmd": "MR",
						"output": [
							"*** TIN REMARKS EXIST *** >*T; ",
							"*** MISCELLANEOUS DOCUMENT DATA EXISTS *** >*MPD; ",
							"*** LINEAR FARE DATA EXISTS *** >*LF; ",
							"ATFQ-OK/$B/:N/Z8/ET/TA1O3K/CCM",
							" FQ-USD 260.00/USD 37.20US/USD 84.33XT/USD 381.53 - 30SEP LAA4OZ2S.LAA4OZ2S.LAA4OZ2S.LAA4OZ2S",
							"GFAX-SSRDOCSCMHK1/////16FEB68/F//MONTROPEZ RUBIO/ORIETTA/DE LOS ANGELES-1MONTROPEZRUBIO/ORIETTA DE LOS ANGELES",
							"   3 SSRDOCSCMHK1/////16FEB68/F//MONTROPEZ RUBIO/ORIETTA/DE LOS ANGELES-1MONTROPEZRUBIO/ORIETTA DE LOS ANGELES",
							"   5 SSRDOCSCMHK1/////16FEB68/F//MONTROPEZ RUBIO/ORIETTA/DE LOS ANGELES-1MONTROPEZRUBIO/ORIETTA DE LOS ANGELES",
							"   7 SSRDOCSCMHK1/////16FEB68/F//MONTROPEZ RUBIO/ORIETTA/DE LOS )><",
						].join("\n"),
					},
					{
						"cmd": "MR",
						"output": [
							"ANGELES-1MONTROPEZRUBIO/ORIETTA DE LOS ANGELES",
							"   9 SSRTKNECMHK01 ORDPTY 0229L 12FEB-1MONTROPEZRUBI.2307407625623C1",
							"  10 SSRTKNECMHK01 PTYBAQ 0635L 12FEB-1MONTROPEZRUBI.2307407625623C2",
							"  11 SSRTKNECMHK01 BAQPTY 0674L 03MAR-1MONTROPEZRUBI.2307407625623C3",
							"  12 SSRTKNECMHK01 PTYORD 0235L 03MAR-1MONTROPEZRUBI.2307407625623C4",
							"  13 SSRCTCECMHK1/ORIETTA502618//ICLOUD.COM-1MONTROPEZRUBIO/ORIETTA DE LOS ANGELES",
							"  14 SSRCTCMCMHK1/17736209227-1MONTROPEZRUBIO/ORIETTA DE LOS ANGELES",
							")><",
						].join("\n"),
					},
					{
						"cmd": "MR",
						"output": [
							"RMKS-GD-ANDROMEDA/104510/FOR ANDROMEDA/104510/LEAD-13267700 IN 2F3K",
							"ACKN-CM EZI5UI   30SEP 1816",
							"><",
						].join("\n"),
					},
				],
				performedCommands: [
					{
						"cmd": "HB:FEX",
						"output": [
							">$EX NAME MONTROPEZRUBIO/ORIETTA DE LOS ANG  PSGR  1/ 1",
							"FARE USD   260.00  TOTAL USD   381.53",
							"TX1 USD   37.20 US   TX2 USD   84.33 XT   TX3               ",
							"",
							"EXCHANGE TKTS ;..............-;...  CPN ALL",
							"TKT1;.............. CPN;.... TKT2;.............. CPN;....",
							"COMM;.........  ORIG FOP;................... EVEN;.",
							"",
							"TTL VALUE OF EX TKTS USD;.............  ORIG BRD/OFF;...;...",
							"TX1 USD;.......;..   TX2 USD;.......;..   TX3 USD;.......;..",
							"ORIG ISS;...... ORIG DATE;....... ORIG IATA NBR;.........",
							"ORIG TKT;..............-;...  ORIG INV NBR;.........",
							"PENALTY USD;............  COMM ON PENALTY;...........",
							"><",
						].join("\n"),
					},
					{
						"cmd": "*MPD",
						"output": [
							"*MPD             MISCELLANEOUS DOCUMENT LIST",
							"          NAME         DOCUMENT NBR   ISSUED       AMOUNT",
							">*MCO1;   MONTROPE    2305056297697   30SEP19          370.53 ",
							"END OF DISPLAY",
							"><",
						].join("\n"),
					},
					{
						"cmd": "*MCO1",
						"output": [
							">HHMCU1           *** MISC CHARGE ORDER ***",
							" PASSENGER NAME;MONTROPEZRUBIO/ORIETTA DE LOS ANGELES...",
							" TO;CM...................................... AT;PTY............",
							" VALID FOR;SPLIT...............................................",
							" TOUR CODE;............... RELATED TKT NBR;.............",
							" FOP;VIXXXXXXXXXXXX1475/OK.....................................",
							" EXP DATE;1022 APVL CODE;510331 COMM;0.00/... TAX;........-;..",
							" AMOUNT;370.53..-;USD EQUIV ;........-;... BSR;..........",
							" END BOX;......................................................",
							" REMARK1;..............................................",
							" REMARK2;......................................................",
							" VALIDATING CARRIER;CM                  ISSUE NOW;.",
							"><",
						].join("\n"),
					},
					{
						"cmd": "*HT",
						"output": [
							"** CURRENT TIN DATA **",
							"MONTROPEZRUBIO-00000000-01/2307407625623/000049884-USD/381.53/TE/30SEP2021Z",
							"** HISTORY TIN DATA **",
							"XK MONTROPEZRUBIO-52983616-17/2305056297697/000049881-USD/370.53/30SEP2013Z",
							"><",
						].join("\n"),
					},
					{
						"cmd": "*HA",
						"output": [
							"     *****  AIR  HISTORY  *****",
							"HS CM 235 L03MAR PTYORD NN/HK1   636P 1115P *       2",
							"HS CM 674 L03MAR BAQPTY NN/HK1   124P  247P *       2",
							"HS CM 635 L12FEB PTYBAQ NN/HK1   948P 1101P *       1",
							"HS CM 229 L12FEB ORDPTY NN/HK1   145P  816P *       1",
							"RCVD-NOKEYSUPPLIEDROBOT/ZDPBVWS -CR- QSB/2F3K/1V AG WS 30SEP1816Z",
							"><",
						].join("\n"),
					},
				],
			},
		});

		return list.map(c => [c]);
	}

	async testCase({input, output, sessionInfo}) {
		const stateful = await GdsDirectDefaults.makeStatefulSession('apollo', input, sessionInfo);
		const cmdRq = input.cmdRequested;

		const actual = await RunCmdRq({
			stateful, cmdRq,
			Pccs: {
				findByCode: (gds, pcc) => Promise.resolve()
					.then(() => Pccs.findByCodeParams(gds, pcc))
					.then(params => SqlUtil.selectFromArray(params, stubPccs)[0])
					.then(nonEmpty('No stubbed PCC matching ' + gds + ':' + pcc)),
			},
		}).catch(coverExc(Rej.list, exc => ({error: exc + ''})));

		actual['sessionData'] = stateful.getSessionData();

		this.assertArrayElementsSubset(output, actual, (actual['userMessages'] || []).join('; ') + '\n');
		this.assertEquals(true, stateful.getGdsSession().wereAllCommandsUsed(), 'not all session commands were used');
	}

	getTestMapping() {
		return [
			[this.provideTestCases, this.testCase],
		];
	}
}

module.exports = RunCmdRqHbFexTest;
